### ISSUE TITLE
Getting rid of bool2int 

### ISSUE THREAD

**Issue by siala** [MiniZinc/libminizinc#100]
Hi,

Since in MiniZinc 2.0 any bool expression can be cast into an int expression, it is probably better to get rid of all the "bool2int" used by the standard flattening from mzn to fzn. The generated fzn files will be smaller. 
An example of such use can be found in libminizinc/share/minizinc/std/among.mzn 

P.S. I wasn't sure where to put my question so I supposed it should be here.

**Comment by skosch** [comment]
just another user here (not a maintainer), but I believe FlatZinc is still at version 1.6 officially, so the solvers consuming your fzns may still rely on those explicit casts.

**Comment by guidotack** [comment]
That's right, the type checker actually inserts bool2int calls into the MiniZinc code, so internally they are still necessary.

**Comment by juliensf** [comment]
Removing them would require all solvers (at least those supporting Boolean and integer variables) to support implicit casts, which may not be the case.   If the aim is to reduce the size of the generated FlatZinc, there's a lot more obvious low hanging fruit that should be addressed before worrying about bool2int.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Comment by cprudhom** [comment]
Hi,
I reopen this issue because I would like to have your opinion on the following proposal:
If it is not possible (is it always the case?) to get rid of `bool2int` constraints, would it not be possible to place them up as the first declared constraints in the FlatZinc format. 
That would ease their detection/substitution during parsing (and avoid a two-pass parsing). 
The objective is not so much to reduce the size of the file (although this is interesting) but also to avoid having to create additional variables and constraints

**Comment by MaxOstrowski** [comment]
I'm unsure if this is really related, but #482 removed a lot of unecessary bool2int from the translations. Still #478 Boolean linear expressions are not correctly handled and create exactly these additional and unecessary variables/constraints that also my solver suffers from. Maybe fixing this already helps ?

**Comment by Dekker1** [comment]
@cprudhom `bool2int` currently cannot be fully removed since there are solvers, Gecode included, that explicitly distinguish between the two types and cannot use booleans in place of integers. For future versions of MiniZinc we are considering a full sub-typing approach for number types, but it is not fully clear yet how this would flow into the solver API. A prototype implementation introduces the `bool2int` channeling only if required.

Although I can imagine that the current situation is not ideal, I wouldn't think that this would incur much overhead. I'm not sure how sorting the FlatZinc from the MiniZinc side would be more efficient. As you said, the best way might be to pass over the constraints before creating the variables.

@MaxOstrowski Although we have removed the `bool2int` from the library, this doesn't mean that these calls have disappeared. The only change is that they are introduced by the compiler instead of manually, which looks a lot cleaner. The current MiniZinc implementation still always lifts types for linear equation.

This is also a current problem for detecting boolean linear expressions. After linear aggregation, the compiler would have to retrace all variables back to their original Boolean version (through `bool2int`) to find that the linear constraint only contains linear variables. Again, this is something that we are hoping to do different in the future.
