### ISSUE TITLE
Array definition with index set not starting with index 1 

### ISSUE THREAD

**Issue by JKBehrens** [MiniZinc/libminizinc#119]
Hello!

According to [the specs](https://www.minizinc.org/downloads/doc-0.8/zinc-spec.pdf)*, the following should be valid:

`array[2..3] of int: myArray = [1, 2];`

I am getting a "index set mismatch" error. Is this a bug?

I wanted to use the index to link to the parent in a tree structure. Since I have two arrays, which both hold possible parents, I wanted to make sure that both arrays use a different sets of indexes.

All the best!
Jan

*
> [M] MiniZinc arrays are maps from fixed integers to values. The index set in
> an array variable declaration must be a contiguous integer range (e.g. 0..3, 10..12,
> or the name of a set variable assigned in the model with a range value), or a tuple
> of contiguous integer ranges. The elements can only be Booleans, integers, floats or
> sets of integers (all fixed or unfixed), or fixed strings.

**Comment by a1880** [comment]
In my understanding, [x, y] is an array with index set 1..2 and thus incompatible in your case. The correct initial expression would be array1d(2..3, [1, 2])

**Comment by JKBehrens** [comment]
Thank you @a1880! That helped. 

I didn't find any example of array usage with an index set not starting with 1 in the available documentation. Maybe this can be made explicit somewhere.

**Comment by Hi-Angel** [comment]
Would be nice though to make compiler to adjust the index set of the right hand side, because the intention in such initialization seems to be quite unambiguous.

**Comment by MaxPowerWasTaken** [comment]
Hey this just tripped me up too, I also found this very confusing and contrary to the documentation. Would you accept a pull request if I submitted one to (attempt to) clarify this in the documentation?

**Comment by guidotack** [comment]
I've improved the error message for this case. In the next release the error message will be
`Index set mismatch. Declared index set of myArray is [2..3], but is assigned to array with index set [1..2]. You may need to coerce the index sets using the array1d function.`

**Comment by MaxPowerWasTaken** [comment]
Thanks a lot for the quick improvement Guido. Would it be possible to also update the documentation in a couple places? I think even the new error message would still be confusing to someone hitting this error for the first time, based on what is in the documentation. For example, [this section](https://www.minizinc.org/doc-2.4.2/en/spec.html#arrays) on declaring arrays:

"""
Explicitly-indexed arrays have index types in the declaration that are finite types. For example:

```
array[0..3] of int: a1;
array[1..5, 1..10] of var float: a5;
```
For such arrays, the index type specifies exactly the indices that will be in the array - the array’s index set is the domain of the index type - and if the indices of the value assigned do not match then it is a run-time error.

For example, the following assignments cause run-time errors:
```
a1 = [4,6,4,3,2];   % too many elements
a5 = [];            % too few elements
```
"""
From the above, I think the clear implication most readers would take away is that the following assignment statement would be valid:
```
a1 = [2,4,6,8];
```
But in fact it throws the same "index set mismatch" as the two incorrect statements listed above which give the wrong number of elements.

Maybe adding one more negative example to highlight this nuance? something like:
"""
`a1 = [2,4,6,8]`   % mismatched index

The last example is most subtle, and occurs because of a mismatched index between the array index declared at instantiation (`[0..3]`), and the implicit [wc? default?] index of list `[2,4,6,8]` assigned to `a1`. The implicit index of list `[2,4,6,8]` is the 1-indexed integer range, `1..4`. 

To use an integer range that does not start with 1 as an array index, use the `array1d` syntax in the assignment statement:
`a1 = array1d(0..3, 2,4,6,8)`
"""
