### ISSUE TITLE
Set literal 1..0

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#12]
The program generates set_eq_reif with one set literal 1..0. Possibly it should be an empty file. I cannot attach the file but can send it on request.

**Comment by krzku** [comment]
Changing set 1..0 to {} in the resulting flatzinc file seems to solve the problem, that is mzn2fzn incorrectly produces set 1..0 instead of {}.

**Comment by guidotack** [comment]
Which solver are you using? 1..0 is a valid representation of the empty set, so this could be a bug in the solver backend.

**Comment by krzku** [comment]
Yes, it is formally correct along the definition from page 4 from flatzinc spec. However, it is not clear at first look that it is {}. You make many transformations during compilation and it would be natural to generate {} instead of 1..0.

BTW, I have already made necessary changes in JaCoP front-end to accept this...

**Comment by guidotack** [comment]
Hi,
the advantage of using 1..0 is that its type is unambiguous, whereas {}
could be a set of int or float or bool.

Cheers,
Guido

-- 
Guido Tack

On 2 Mar 2015, at 20:31, krzku <notifications@github.com> wrote:

Yes, it is formally correct along the definition from page 4 from flatzinc
spec. However, it is not clear at first look that it is {}. You make many
transformations during compilation and it would be natural to generate {}
instead of 1..0.

BTW, I have already made necessary changes in JaCoP front-end to accept
this...

—
Reply to this email directly or view it on GitHub
<https://github.com/MiniZinc/libminizinc/issues/12#issuecomment-76681321>.

**Comment by krzku** [comment]
OK. I get it! Does it means that a bool empty set will be true..false?

BTW, the following simplified (stupid) code that I used to try different cases generates segmentation fault.

var set of bool: b;
var set of bool: bb;

constraint
	b union {} = bb;
 
Cheers,
Kris

**Comment by guidotack** [comment]
Thanks for the report.  MiniZinc doesn't support var set of bool (the only var set type supported is int), but the type checker had a bug and didn't report that as an error.  It's already fixed and will be part of the next release.

An empty bool set would be true..false and an empty float set would be 1.0..0.0, although the compiler won't currently generate those because they should only occur in par expressions (and no constraints take par sets of bool/float as arguments as far as I can see).

Cheers,
Guido
