### ISSUE TITLE
mzn2fzn-2.0.1 generates undocumented count_eq_reif constraints

### ISSUE THREAD

**Issue by scand1sk** [MiniZinc/libminizinc#13]
When I launch mzn2fzn on amaze problems from the 2014 challenge with a redefined `count_eq` predicate, mzn2fzn generates `count_eq_reif` constraints which are undocumented in the FlatZinc specification. Is it a new constraint that should be implemented?

**Comment by scand1sk** [comment]
I added the following redefinition as a (temporary?) workaround:

    predicate count_eq_reif(array[int] of var int: x, var int: y, var int: c, var bool: r) = 
      let { var int: v } in count_eq(x, y, v) /\ int_eq_reif(v, c, r);

**Comment by guidotack** [comment]
Hi,

that's a limitation in the current library design.  Whenever there's a builtin for a constraint, if it occurs in a reified position, the reified version also needs to be defined. This has two problems currently: you don't get a compiler error if the reified builtin is not defined, and you don't automatically get the decomposition from the standard library as the reification.
Your workaround solves part of the problem, but we have plans to restructure the library soon so that we have a standard _reif version for every constraint that the compiler can fall back on.

Cheers,
Guido

> On 11 Mar 2015, at 2:07 am, Julien Vion <notifications@github.com> wrote:
> 
> I added the following redefinition as a (temporary?) workaround:
> 
> predicate count_eq_reif(array[int] of var int: x, var int: y, var int: c, var bool: r) = 
>   let { var int: v } in count_eq(x, y, v) /\ int_eq_reif(v, c, r);
> —
> Reply to this email directly or view it on GitHub <https://github.com/MiniZinc/libminizinc/issues/13#issuecomment-78073360>.
> 

-- 
Guido Tack,
http://www.csse.monash.edu/~guidot/

**Comment by informarte** [comment]
I encountered the same problem when applying mzn2fzn-2.0.10 to the amaze problem of the 2012 challenge. I wonder when the FlatZinc specification will be updated accordingly? For the time being, which predicates should be defined in addition to what the latest specification (version 1.6) requires?

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
