### ISSUE TITLE
Please improve readability of compiler output

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#147]
As author of a FlatZinc backend, I frequently read output of mzn2fzn and there are two things that make reading it harder than necessary:

1. Introduced variables have a number, e.g. X_INTRODUCED_22. So when searching for occurrences of this variable, we also find X_INTRODUCED_220, etc, unless one uses a regexp. This problem could be avoided by introducing leading 0s, e.g. X_INTRODUCED_0022, as mzn2fzn 1.6 did it.

2. It seems to me that mzn2fzn introduces a new variable for each problem variable and then often uses the introduced variable instead of the problem variable. This behaviour makes it very hard to connect the FlatZinc model to the MiniZinc model. I remember that mzn2fzn 1.6 used the problem variables and that its output was way more readable.

**Comment by guidotack** [comment]
1. I've pushed a fix so that variables with numeric ids will now be printed as X_INTRODUCED_n_ (with a trailing underscore).
2. We will add functionality to generate a mapping from FlatZinc names to MiniZinc names soon (as a separate output, without modifying the generated FlatZinc). It should be very easy to write a little tool that applies the mapping to the generated FlatZinc as well.

**Comment by informarte** [comment]
Thanks for the trailing underscore!
