### ISSUE TITLE
any support for Z3 solver?

### ISSUE THREAD

**Issue by yogeshVU** [MiniZinc/libminizinc#161]
feature request: would be nice to have support for the Z3 solver

**Comment by guidotack** [comment]
There's a converter from FlatZinc to SMT-LIB format at http://ima.udg.edu/Recerca/lap/fzn2smt/
I haven't tried it myself but I've heard that it still works with current versions of MiniZinc.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Comment by jarble** [comment]
@Dekker1 and @guidotack: Are there no plans to support Z3 as a solver for MiniZinc? A FlatZinc-to-SMT-LIB converter is still available [here](https://ima.udg.edu/Recerca/LAI/fzn2smt/index.html).

**Comment by Dekker1** [comment]
Although an SMT interface from MiniZinc would certainly be valuable, we currently don't have any plans to create such an interface due to time constraints of the MiniZinc team.

If, however, someone wants to get their hands dirty, then I would urge them to contact us. I certainly have some ideas of how such an interface would work, and I would be very happy to mentor someone in writing the solver backend.
