### ISSUE TITLE
Trivial equality unsatisfiable

### ISSUE THREAD

**Issue by Martin8X** [MiniZinc/libminizinc#169]
```
include "globals.mzn";
var 0..9: A_1_1;
var 0..9: A_2_1;
var 0..9: A_3_1;
constraint (A_3_1+A_2_1+A_1_1) = A_1_1;
solve satisfy;

```
The model should have the trivial solution 0=A_1_1=A_2_1=A_3_1. However, Gecode and other solvers report this as unsatisfiable.

**Comment by a1880** [comment]
Using `Gecode `and `G12fd `from within the `MiniZinc 2.1.5 IDE`, I tried as slightly modified example with similar effects:

```
set of int: t = 0..1;
var t: A;
var t: B;
var t: C;
constraint (A + B + C) = A;
solve satisfy;
```

This resulted in 


```
  WARNING: model inconsistency detected
E:/AK/TEXTE/Knowhow/MiniZinc/Untitled1_20170711.mzn:6:
  in binary '=' operator expression
Running Untitled1_20170711.mzn
=====UNSATISFIABLE=====
% E:/AK/tmp/MiniZinc IDE (bundled)-sOHtmx/Untitled1_20170711.fzn:1: warning: model inconsistency detected before search.

```
It did not help to replace `=` by `==`

**Comment by hakank** [comment]
From my answer of this question on StackOverflow (https://stackoverflow.com/questions/45010231/minizinc-trivial-equality-unsatisfiable):

It seems to be a bug in MiniZinc when it translates the model to FlatZinc format. The message given is from MiniZinc:
```
WARNING: model inconsistency detected
test66.mzn:6:
in binary '=' operator expression
```
The generated FlatZinc file contains just this:
```
constraint bool_eq(false,true);
solve  satisfy;
```
and that's why the FlatZinc solvers yield UNSATISFIABLE.

Interestingly, the following model works, using a temporary decision variable, T:
```
var 0..9: A_1_1;
var 0..9: A_2_1;
var 0..9: A_3_1;
var 0..9: T;
constraint
    T = A_3_1 + A_2_1 + A_1_1 /\
    T = A_1_1
; 
solve satisfy;
```
The model then yield all 10 solutions with A_1_1 is assigned values from 0 to 9, A_2_1 = A_3_1 = 0, and T is assigned to same value as A_1_1.

However, if T is initialized with A_1_1 then UNSAT is thrown again:
```
var 0..9: T = A_1_1;
```

One can note that the following constraint works, i.e. 2 * A_1_1 at the right side:
```
constraint A_3_1 + A_2_1 + A_1_1 = 2 * A_1_1;
```

**Comment by schutta** [comment]
MiniZinc 1.6 correctly processes the model. The problem starts to occur from MiniZinc 2.0.0, I tested 2.0.{0,1,2,4,6,7,8} and 2.1.{0,4,5}.

Interestingly, the following model will be correctly processed by any MiniZinc version.
```
var 0..1: A;
var 0..1: B;
constraint A + B = A;
solve satisfy;
```

**Comment by guidotack** [comment]
Yes, this was a nasty one... It's fixed in the develop version now, I'll push a new release in the next few days.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
