### ISSUE TITLE
mzn2fzn: Predicate calls are skipped

### ISSUE THREAD

**Issue by schutta** [MiniZinc/libminizinc#178]
The compilation of the following MiniZinc model `test_pred.mzn` is not executed correctly.
```
int: n = 3;
int: z = 20; 
set of int: I = 1..n;
array[I] of var int: x = [21, 22, 23];
array[I] of var int: y;

predicate my(var bool: b, string: msg, bool: debug) = ( 
    trace("\tCall my/3: \(debug)\n") /\
    if debug /\ is_fixed(b) then
        if fix(b) then true else
            trace(msg)
         endif
    else
        b   
    endif
);

constraint forall(i in I)( 
    trace("X: i = \(i):\n") /\
    my( z > x[i], "\t-> Error\n", true)
);

constraint forall(i in I)( 
    trace("Y: i = \(i):\n") /\
    my( z > y[i], "\t-> Error\n", true)
);

solve satisfy;
```

The expected output for compilation `mzn2fzn test_pred.mzn` is:
```
X: i = 1:
	Call my/3: true
	-> Error
X: i = 2:
	Call my/3: true
	-> Error
X: i = 3:
	Call my/3: true
	-> Error
Y: i = 1:
	Call my/3: true
Y: i = 2:
	Call my/3: true
Y: i = 3:
	Call my/3: true
```
However, it seems that the call of the predicate `my/3` is skipped for `X: i = 2` and `X: i = 3`. Here the output.
```
X: i = 1:
	Call my/3: true
	-> Error
X: i = 2:
X: i = 3:
Y: i = 1:
	Call my/3: true
Y: i = 2:
	Call my/3: true
Y: i = 3:
	Call my/3: true
```

MiniZinc 2.1.5

**Comment by guidotack** [comment]
Can you please post a complete example? The one above is missing declarations for I, x and z.

**Comment by schutta** [comment]
Updated the original post.

**Comment by guidotack** [comment]
That behaviour is due to Common Subexpression Elimination, and it's actually correct.

For i=1, it calls my(false, "\t-> Error\n", true), which results in the output. For i=2, it again calls my(false, "\t-> Error\n", true), and CSE prevents that call from being evaluated again (since we already know the result), and the same for i=3.

Predicates and functions in MiniZinc are assumed to be pure, but of course introducing side effects (like trace) means that these optimisations become observable.
