### ISSUE TITLE
Induction definitions in Minizinc

### ISSUE THREAD

**Issue by hooman650** [MiniZinc/libminizinc#201]
Is there a way to express inductive definitions in Minizinc (e.g. reachability)? Say I have a transition function that defines the next state of my model based on its current state. I would like to check whether starting from an initial state , within a certain number of transitions, a goal state is reachable. Here is a simple example:
```
% Check for 1 transition starting from Initial_ST
int: L=3;              
  
 % Holds the simulation from start to end(length of L)                                                    
array[1..L,1..4] of var bool: Transition;  

% Constraint the start of transition to be Initial_St                      
constraint forall(i in 1..4)(Transition[1,i]=Initial_St[i]);   

% Initial State to be enforced
array[1..4] of int: Initial_St = [0,0,1,0];   

 % Goal State to check whether its reachable from Init                     
array[1..4] of int: Goal_S= [1,1,1,1];                            

% Goal is reachable?
constraint  forall(i in 1..4)(Transition[L,i]=Goal_S[i]);                                                                 

% Call Predicate
constraint  ComputeTransition(Transition, L);                                                               

% Computes Transition 
predicate ComputeTransition(array[int,int] of var bool: T, int: nrow)=
forall(i in 2..nrow)(
         forall(j in 1..4)(
                         T[i,j] = exists(k in 1..4 where k != j)(T[i-1,k])   % Just a simple transition function example
));

solve satisfy;
output [show(Transition[i,j]) ++ " " ++
         if j == 4 then "\n" else "" endif |
         i in 1..L, j in 1..4 ];
```
Here the number of transitions is L and is fixed, I was wondering there might be a smart way to increase L (starting from 2 for instance ) automatically until the instance becomes satisfiable (e.g. Initial state is reachable to goal state). Currently, I have to manually increase L starting from 2 and run the model if unsat increase it again and run again. So is there a way to automate such a thing? Say run this for L in 2..100, but stop increasing L if it is satisfiable ? Something like bounded model checking... 
Thank you in advance for any advice on this,,,,
Cheers
Hooman

**Comment by Dekker1** [comment]
Hi Hooman,

The first thing that comes to mind are the [`regular` and `regular_nfa` predicates](http://www.minizinc.org/doc-lib/doc-globals-extensional.html). These predicates take an automaton, DFA or NFA, and then check a list of integer which are required to be accepted by the automaton. If you now encode your states as the values accepted by the automaton and use the automaton to constrain which state transitions are valid, then these predicates should do exactly what you're currently doing in your model but will be natively supported by some solvers and might have better deconstructions.

Because of the modeling restrictions, a variable has to be created for every possible state within the time frame. If however you know that the goal/accepting state can be reached early, a modelling trick is to direct all accepting state to a dummy state, which is still an accepting state, accepts a dummy value, and transitions back to itself. The actual length that is used can be determined using another variable:
```
int: maxlen;
var 1..maxlen: len;
constraint forall (i in len+1..maxlen) (
  value[i] = dummy
);
```

Since shorter transitions might be preferred, you might want to consider `len` in your objective. `solve minimize len;` will give you the shortest list of transitions possible, if the model is satisfiable. This strategy might be sped up by using a search strategy that prefers smaller `len`.

Let us know if this solves your problem.

**Comment by hooman650** [comment]
Hi Jip,

Excellent tips! Thank you! Yea, the regular predicate sounds promising for this and reachability analysis, though in my case since sometimes I deal with transition functions that themselves contain decision variables, so I am looking at the regular.mzn to write a similar predicate that would handle decision variables in the transition function but I understand that then it wont be able to use the deconstruction power of specific solvers. Your second suggestion is also interesting, I try to implement both and see which one performs better and update on the same threat! 
Thanks to you guys, now minizinc enables easy comparison of solvers and even techniques (SAT, LCG, etc), so in this case I am trying to compare the bounded model checking power of different solvers. 

Cheers,
H

**Comment by Dekker1** [comment]
It seems the work your referring to extended the solver [chuffed](https://github.com/chuffed/chuffed) with `normal_rule` as a solver predicate. To my knowledge this predicate never appeared in MiniZinc's own globals library and a quick search doesn't reveal it to be in chuffed's current library. My suggestion would be to email the authors of the paper to see what happened to the implementation that they used.

Since the problem seems to be on the modelling side, not a problem with the compiler, I will close this issue (or correct me if I'm not understanding it correctly). Feel free to ask more questions; perhaps [StackOverflow](https://stackoverflow.com/questions/tagged/minizinc) or the [Google group](https://groups.google.com/forum/#!forum/minizinc) would be more suited places to continue this conversation.
