### ISSUE TITLE
flattening with when clause that includes a predicate does not work well.

### ISSUE THREAD

**Issue by oferst** [MiniZinc/libminizinc#223]
Consider the following model, that shows what happens when you use a predicate in a 'when' clause. The where clause can be evaluated statically in both cases.  

int : n_course = 5;
set of int : r_course  = 1..n_course;
array [r_course] of 0..1   : class = array1d(r_course,[1,1,1,0,0]);
var int: x;

% This line works correctly and prints 123 as it should. The model is simplified to a trivial instance. 
constraint sum(c in r_course where class[c]==1)(trace(show(c),1)) == x; 

% on the other hand this constraint, which is identical to the previous one but uses an explicit predicate, 
prints 111222333444555 as it should not, and is not simplified to a trivial instance. 

predicate is_class(r_course:c) = class[c]==1;
constraint sum(c in r_course where is_class(c))(trace(show(c),1)) == x; 
solve satisfy;

This may seem trivial but in my case this was the difference between a model that could not be compiled even on a 64GB machine, and a model that could compile on an 8GB machine.

**Comment by guidotack** [comment]
Thanks. This is due to the fact that the type of a predicate is always var bool, which means that the where clause cannot necessarily be evaluated statically. There is another keyword in MiniZinc, "test", that describes a "par bool predicate":

`test is_class(r_course:c) = class[c]==1;`

should have the desired behaviour. I will change the type checker to automatically turn a predicate into a test if its body is par.
