### ISSUE TITLE
json parser infers wrong dimensions for 2D-arrays with dims equal to 1

### ISSUE THREAD

**Issue by random-** [MiniZinc/libminizinc#268]
Using the develop branch (e154e9da) I get an unexpected  'Index set mismatch' evaluation error for 2D arrays that have dimensions equal to 1.

Minimal reproducer follows.
In the dzn file:
```
array[1..1, 1..2] of var 0..1: variable;
```

In the json data file:
```
{
   "variable":[[0,0]]
}
```

Removing the condition dims[curDim].second>0 in the following line of lib/json_parser.cpp fixes the issue:
```
 if (!hadDim[curDim] && dims[curDim].second>0)
```

**Comment by Dekker1** [comment]
It seems the initial implementation of our JSON parser was trying to be smart by only counting the commas instead of the elements. The problem with this approach is that there is always one less comma than there are elements, meaning you have to add one to the number of elements at the end. The problem now is empty lists: you should not count an extra element when you encounter an empty list. The expression `dims[curDim].second>0` is to guard against this problem.
As you found out, this guard is incorrect for singletons, as no elements have yet been counted.

There might be a correct solution to counting commas instead of elements, but all of them would require the use of a stack structure. Instead I've changed the code to count the actual elements instead.

**Comment by random-** [comment]
I was suspecting that the condition was there for a good reason but I didn't think about empty arrays...

Thanks for the reactivity and the fix!
