### ISSUE TITLE
MiniZinc 2.2.3: Issues with command-line interface

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#271]
I noticed some issues with the command line of minizinc 2.2.3:

- The parameter to the -p option is not passed on to the backend as is but as the corresponding binary value, i.e. -p 2 is turned into -p ^B, for example.

- There is no way to pass parameters to the backend.

- When using Gecode as backend to solve an optimization problem, intermediate solutions are not printed, only the optimal solution.

All these problems do not occur in the MiniZinc IDE.

**Comment by Dekker1** [comment]
Thank you for reporting your problems. The first issue was indeed a bug within the MiniZinc driver. I've pushed a fix to the development brach,

The current way of passing flags to a FlatZinc solver is to use the `--fzn-flags` MiniZinc flag. A string with options can follow this flag. For example: `minizinc --solver gecode -p 4 -a --fzn-flags '-restart none' test.mzn`

The last issue is expected behaviour of MiniZinc, you have to pass the `-a` flag to gecode to print intermediate solutions. (The IDE adds this option be default).

**Comment by informarte** [comment]
Thanks for fixing -p.

I looked for documentation of `--fzn-flags`. The MiniZinc handbook mentions its existence in the section on FindMUS subsolver options but does not document the option per se. `minizinc --help` does not list `--fzn-flags` either.
