### ISSUE TITLE
Solvers not detected in spite of *_HOME variables

### ISSUE THREAD

**Issue by SebAlbert** [MiniZinc/libminizinc#280]
Similar to #228 I found that libminizinc (running `mzn2fzn` or `minizinc`) do not list any solvers (by the `--solvers` option) after fresh compilation from current master branch (gcc 8.2 on Gentoo), even though I had set the `GECODE_HOME` and `GUROBI_HOME` environment during all `cmake` steps.

(Worse, even the MiniZincIDE didn't help (as I had hoped from reading the manual), since a fresh build of that does not include any configuration files either.)

What might I have done wrong?

**Comment by Dekker1** [comment]
Hi,

There are a few things that might not be documented well that you'll need to know:

- Solver locations are no longer signalled to CMake using the `XX_HOME` variables, but since the CMake refactoring `XX_ROOT` is used to be aligned with the standard CMake FindModules. (e.g., `GECODE_ROOT`)
- `--solvers` will not show the solvers that are marked internal. This applies to Gecode as the solver interface compiled with MiniZinc is currently not the standard Gecode to be used (the bundles still use `fzn-gecode`). The internal Gecode solver can be used using `--solver presolver`.
- Plugin solvers, solver that require software being installed to run, are only shown if found on your system and might need a special flag. This applies to Gurobi and CPLEX as the solvers themselves are by default not build into the MiniZinc executable. If the solvers are not automatically found on your system you can either provide their location at runtime (e.g., using the `--gurobi-dll` flag), or compile them into your executable using`-DUSE_PROPRIETARY=ON -DGUROBI_PLUGIN=OFF -DCPLEX_PLUGIN=OFF`.
- The MiniZincIDE repository does not provide any solvers itself, but does contain the configurations for external solvers that are shipped with MiniZinc. These configuration files can be found in `resources/solvers`.

I hope this helps.
