### ISSUE TITLE
findMUS command line doesn't work

### ISSUE THREAD

**Issue by ceandrade** [MiniZinc/libminizinc#284]
Hi guys,

I know this is not a libminizinc issue and both "globalizer" and "findMUS" codes are not opened yet. However, I need to use these tools from command line / bash scripts, and I have no success. I tried both on Mac OS X Mojave and Ubuntu 19.04.

This issue has a following up ticket #285.

First, "findMUS" does not accept any combination of arguments we pass to it. Here what is happening both Ubuntu and Mac using the latin squares example. Note first I created the FZN calling Minizinc to do that:

```bash
[ubuntu-vm:~/temp]
$ ls
latin.fzn  latin.mzn

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn
Path file latin.paths cannot be opened.
findMUS: Explain an unsatisfiable model
  usage: findMUS <flatzinc file> [paths file]
                 [-a] [-n <n>]
                 [--ignore-unsat-background]
                 [--structure {normal, flat, gen, mix}]
                 [--binarize {none, leaves, all}]
                 [--depth {mzn, fzn, i}
                 [--verbose-{enum,map,subsolve} <v>]
                 [--verbose]

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn latin.paths
Path file latin.paths cannot be opened.
findMUS: Explain an unsatisfiable model
  usage: findMUS <flatzinc file> [paths file]
                 [-a] [-n <n>]
...

[ubuntu-vm:~/temp]
$ touch latin.paths

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn latin.paths
Segmentation fault (core dumped)
```

So, I understand that `findMUS` should write a "paths" file, but it doesn't if called only with fzn file. But, if we create an empty file, we get a segfault.

Then, I noticed that `minizinc` has an option to "keep paths", so that I regerated the FZN file:

```bash
[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver OSICBC --keep-paths latin.mzn --fzn latin.fzn 
=====UNSATISFIABLE=====

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn 
Segmentation fault (core dumped)
```

Now we have the paths, but `findMUS` keeps resulting on segfault.

So, I tried to use `minizinc` command line directly, but it also fails. I'll open another ticket to that.

Interesting enough, it works from the GUI. So, it looks like some option or option order is important here.

**Comment by lokdlok** [comment]
Hi,

`~/MiniZincIDE-2.2.3/bin/minizinc --solver OSICBC --keep-paths latin.mzn --fzn latin.fzn`
Tries to solve the model and saves the .fzn file.

You have to run `minizinc -c` or `mzn2fzn` to force it to only compile.
Also, I recommend using the `--output-paths` option instead of `--keep-paths`.
They should both work, but the `--keep-paths` option will bloat the `.fzn` file with path annotations that aren't needed by `findMUS`.

Try running the following and let us know if it works:
``~/MiniZincIDE-2.2.3/bin/minizinc -c --solver OSICBC --output-paths latin.mzn``
This should produce the files: `latin.fzn`, `latin.ozn`, and `latin.paths`
