### ISSUE TITLE
long variable names

### ISSUE THREAD

**Issue by zuozp8** [MiniZinc/libminizinc#291]
running
```
int: nc = 4;

var 1..nc: wa;    var 1..nc: nt;
var 1..nc: sa;    var 1..nc: q;
var 1..nc: nsw01012345012345;   var 1..nc: v;
var 1..nc: t;

constraint wa != nt;
constraint wa != sa;
constraint nt != sa;
constraint nt != q;
constraint sa != q;
constraint sa != nsw01012345012345;
constraint sa != v;
constraint q != nsw01012345012345;
constraint nsw01012345012345 != v;

solve satisfy;
```
with `minizinc foo.mzn` gives me error `MiniZinc: internal error: not declmap.end()!=it:  solns2out_base: unexpected id in output: nsw01012345012345`

making that long variable one character shorter solves the problem

i use `minizinc/minizinc:edge` docker image

**Comment by guidotack** [comment]
I can't reproduce the problem here, how exactly do you call minizinc? I'm using the following command line:
`docker run --rm -it -v $PWD:/model  minizinc/minizinc:edge minizinc /model/foo.mzn`
Perhaps there's something strange going on with the file system (e.g., perhaps there's an old file `foo.ozn` that minizinc still finds from a previous run).

**Comment by zuozp8** [comment]
i didn't notice that i had some old image downloaded, after pulling fresh minizinc/minizinc:edge problem is solved

problem was with `minizinc/minizinc@sha256:b0bd96f4f8b469571c86ffc0538e2839088d3f22757208ee0024eb8ab7446f2d`

thak you for help
