### ISSUE TITLE
"is" models became larger since MiniZinc 2.2.2

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#312]
Regarding the "is" instances from the MiniZinc benchmarks library, I noticed that MiniZinc 2.3.0 produces larger models for them than MiniZinc 2.2.2. In particular, the number of `array_bool_or` constraints increased, slowing down solvers. Please find attached the models for the jZ9pQqRxJ2 instance. Compilation was for my solver [Yuck](https://github.com/informarte/yuck) and without any optimization flags. I also tried MiniZinc 2.3.1 with -O3 but that did not help.

[is-jZ9pQqRxJ2-minizinc-2.2.2.fzn.gz](https://github.com/MiniZinc/libminizinc/files/3565545/is-jZ9pQqRxJ2-minizinc-2.2.2.fzn.gz) with 3 `array_bool_or` constraints
[is-jZ9pQqRxJ2-minizinc-2.3.0.fzn.gz](https://github.com/MiniZinc/libminizinc/files/3565546/is-jZ9pQqRxJ2-minizinc-2.3.0.fzn.gz) with 151 `array_bool_or` constraints

**Comment by guidotack** [comment]
The 2.3.0 compiler introduced a number of changes in the compilation of Boolean clauses. You can see in the examples that you attached that while the number of array_bool_or constraints has gone up, the number of bool_clause constraints has gone down (although not by quite as much). For this particular model, it may be slightly disadvantageous because the compiler is now missing some common subexpressions that it found before, but for other models the trade off will be the other way around.
