### ISSUE TITLE
Checking instance for non-contiguous range 

### ISSUE THREAD

**Issue by ceandrade** [MiniZinc/libminizinc#313]
Assume that we have the following model:

```mzn
% model
set of 0..10: values;
array[values] of var 0..1: x;
solve minimize sum(x);

% data
values = 1;
```

Note that in the data section, `values` is declared with the wrong type: there, it is a single `int`, but in the model `values` should be `set of int`. In this case, minizinc works fine:

```bash
$ minizinc --model-check-only model.mzn 
unknown file:0.0:
MiniZinc: type error: initialisation value for `values' has invalid type-inst: expected `set of int', actual `int'
multiple type errors

$ minizinc --instance-check-only model.mzn 
unknown file:0.0:
MiniZinc: type error: initialisation value for `values' has invalid type-inst: expected `set of int', actual `int'
multiple type errors
```

Now, let's change to

```mzn
values = {1, 2, 4};
```

Note that now `values` type is correct (`set of int`). However, variable `x` in the original model is an array indexed by `values`, and according to current minizinc requirements, `values` must be a contiguous range. However, `values` is not a non-contiguous range. Therefore, we should have an error when checking the data:

```bash
$ minizinc --model-check-only model.mzn 
# No error, this is correct.

$ minizinc --instance-check-only model.mzn 
# No error. This should be incorrect since the data (instance) is not 
# conforming with the model. In other words, the instance is incorrect.

$ minizinc -c model.mzn --fzn model.fzn 
MiniZinc: evaluation error: 
  /Users/cea/temp/model.mzn:3:
  in variable declaration for 'x'
  array index set must be contiguous range
```

Note that we have to compile the whole model to get an error, although other basic checkings (syntax and types) are done with `--instance-check-only`, as shown before. However, IMHO, this is a data/instance error and should be reported during the checking too, not only during the flattening. However, I understand that such a thing can be challenging to do due to the structural changes that must be done.

Note that this, let's say, "inconsistence" on reporting errors, causes bugs in other packages (see this issue on pymzn package: https://github.com/paolodragone/pymzn/issues/43).

**Comment by Dekker1** [comment]
Hi @ceandrade,

Thank you for your patience. This issue suggests that the `--model-check-only` or the instance version should report the issue that a non-contiguous set is used as the index set to an array. As this is currently not evaluated during type-checking the problem is actually not found in the MiniZinc checking mode.

It is a bit different from the first error as the guarantee of the right type does not necessarily guarantee that the data is available to evaluation the index set. (For example when it's a set comprehension that depends on data that is unavailable). Although I will admit that it would make sense to add a check, when possible, during type-checking to show this problem in IDE's and programmatically, but the possibility of the evaluation error will always remain.

As there are other problems that can only be caught during the evaluation of MiniZinc, the real problem in your case seems that pymzn is not correctly marking the status as `ERROR`, but as `INCOMPLETE`.

**Comment by guidotack** [comment]
In general, array index set errors can only be caught during evaluation (you can think of them as similar to array out of bounds errors). We could potentially add checks for index sets that are given as set literals, but this would only catch some of the errors during `--instance-check-only`. For the time being, this behaviour is not going to change.
