### ISSUE TITLE
length function bug

### ISSUE THREAD

**Issue by markwallacemonash** [MiniZinc/libminizinc#315]
array [1..3] of var 1..3:X;
constraint X = [1,1,1] ;
var 0..3: obj;
constraint obj = length([i| i in 1..3 where X[i]>1]) ;
solve satisfy ;

Succeeds with
obj = 3;
for gecode, chuffed, gurobi - presumably all solvers

**Comment by Dekker1** [comment]
Hi Mark,

This is actually expected behaviour. `[i| i in 1..3 where X[i]>1]` is a array comprehension that will return a `array[int] of var opt int` type. An explanation about why a array with optional types has unexpected lengths can be found here: https://www.minizinc.org/doc-latest/en/optiontypes.html#hidden-option-types

A solution to your small model here would be to use a sum over boolean values instead:
```
array [1..3] of var 1..3:X;
constraint X = [1,1,1] ;
var 0..3: obj;
constraint obj = sum([X[i] > 1| i in 1..3]) ;
solve satisfy;
```

**Comment by markwallacemonash** [comment]
Sorry, Jip - I had forgotten I was introducing an optional type :-(
I did indeed use sum...
Thanks for being so quick!
    Cheers
        Mark

*Mark Wallace  *
Professor
*Information Technology*
Monash University, Level 6, Building H, Caulfield Campus, 900 Dandenong
Road, Caulfield East VIC 3145, Australia
T: +61 (0)3 9903 4276                      M: +61 0400 868 629
                E: mark.wallace@monash.edu <name.surname@monash.edu>

*We acknowledge and pay respect to the Traditional Owners and Elders -
past, present and emerging - of the lands on which Monash University is
located.*
