### ISSUE TITLE
make install does not create PREFIX/share/minizinc/solvers

### ISSUE THREAD

**Issue by jwaldmann** [MiniZinc/libminizinc#326]
I build minizinc from source with `cmake -DCMAKE_INSTALL_PREFIX=/what/ever`.

 `make install` puts it in the expected location, but `/what/ever/share/minizinc/solvers` is missing. 

I expect the directory is present and contains the solvers that I specified when building - in my case, gecode, see https://github.com/MiniZinc/libminizinc/issues/249#issuecomment-541321279

**Comment by guidotack** [comment]
The built-in interface to Gecode is still a bit different from the external `fzn-gecode` tool that ships with the MiniZinc binary distribution. The internal solvers (such as this Gecode, but also Gurobi, CBC etc) don't need a configuration file in the `share/solvers` directory, their configuration is hard-coded in the C++ interface code. Since the internal Gecode currently doesn't support all the features of `fzn-gecode` yet, it doesn't show up as a solver (e.g. in the `--solvers` list), but you can still use it with the `--solver gecode_presolver` command line option.
