### ISSUE TITLE
Honoring add_to_output

### ISSUE THREAD

**Issue by marcovc** [MiniZinc/libminizinc#328]
Hi,

I'm finding out that libminizinc sometimes does not include a variable annotated with ::add_to_output in the resulting .fzn file.

One case it doesn't is when the variable is functionally dependent on an expression, e.g.

```minizinc
var int: v::add_to_output = sum(other_vars);
```

Here the resulting fzn file does not mention v, which is ok since I thought I could get away with:

```minizinc
var 0..10: v::add_to_output;
constraint v = sum(other_vars);
```

but unfortunately (!) at times mzn is clever enough to remove v from the fzn file anyway.

I tried "output_var" and several other annotations, but nothing seems to work.

Is this expected? If so, is there a way I can force the variable to be included in the fzn file?

Thanks!

**Comment by Dekker1** [comment]
Hi Marco,

The `add_to_output` annotation only guarantees that the variable is included in the output. For example in your case, you seem to have a sum of variables that is included in the output, but the sum is never constrained in the instance. To unburden the solver, we do not post a sum constraint and instead construct the sum in the output model. (The ozn file that is generated should have this sum somewhere). Remember that first flattening an instance and then running a flatzinc solver is not the full process! You also have to run it through the output processor, what used to be called `solns2out`. This is included when you run the `minizinc --solver XXX model.mzn data.dzn` command.

We do not have any mechanism to guarantee a variable to be included in the FlatZinc, but this might not be as much of a problem as you think. For users of MiniZinc having something in the FlatZinc is not important as long as the output is as they required and a solver should probably be happy with any work that can be avoided. When testing FlatZinc solvers, you might sometimes want to ensure something is included. There are two good options for this: either you manually create a FlatZinc file and test the exact functionality you were hoping to get from the MiniZinc compiler, or, when possible, you add an redundant/implied constraint on the variables you want to include. Note that this is what happened in the second case: you not only constructed a new variable with the sum of other variables, but you also constrained it to be between 0..10. Because it's now no longer a simple functional definition, the compiler won't remove the constraint. `var 0..10: v::add_to_output = sum(other_vars);` should have had the same effect

**Comment by marcovc** [comment]
Hi Jip,

Thanks.

I did not make myself clear: in seems that in the second case, sometimes the compiler also excludes the variable (or I guess it gets renamed to one of those introduced variables).

My use case is a bit contrived. I am using libminizinc to get from minizinc->flatzinc and then I'm using gecode to get from flatzinc->FlatZincSpace. This is great: a high level declarative language to quickly model the problem, with all the powerful gecode primitives to control search. And it seem works very well, I am able to reflect back the variables I want to branch/output on from the FlatZincSpace. Except for this problem: sometimes a variable vanishes from the created FlatZincSpace, because it is not even in the flatzinc file generated by libminizinc.

Anyway, just to give you the context. I understand that this is an exceptional use.

Thanks anyway!
Marco

**Comment by guidotack** [comment]
If you want to force variables to stay in the generated FlatZinc, you can introduce your own solve annotation that just serves as a "keep-alive" marker:
```
var int: v::add_to_output = sum(other_vars);
annotation my_search(array[$T] of var int:x);
solve ::my_search([v]) satisfy;
```

**Comment by marcovc** [comment]
That will do the job, thanks!
