### ISSUE TITLE
MiniZinc: type error: undefined identifier `X_INTRODUCED_50_'

### ISSUE THREAD

**Issue by tomerv** [MiniZinc/libminizinc#336]
I'm new to MiniZinc, so please let me know if I'm doing something stupid.

This is my model:

```
int: n = 10;
array[1..n] of var 1..n: a;
```

That's it. Now I want to print a solution:

`output [join("  ", [show_int(2, x) | x in a])];`

This is fine (it prints "1 1 1 1 1 ..."). But now I want to "refactor" this output line by using an intermediate variable while preserving the same behavior:

```
array[1..n] of string: A = [show_int(2, x) | x in a];
output [join("  ", A)];
```

This causes MiniZinc to break in various ways, depending on the way I'm running it and the value of n:

- In the IDE with n = 10 I get this output: `X_INTRODUCED_0_  X_INTRODUCED_1_  X_INTRODUCED_2_  X_INTRODUCED_3_  X_INTRODUCED_4_  X_INTRODUCED_5_  X_INTRODUCED_6_  X_INTRODUCED_7_  X_INTRODUCED_8_  X_INTRODUCED_9_`
- In the IDE with n = 50 I get this error message: `MiniZinc: type error: undefined identifier `X_INTRODUCED_50_' ` (sadly, the temporary files are not saved, so I can't see what's going on exactly).
- In the command-line tool I get a printing similar to the n=10 case in the IDE, even when n = 50. When I look into the fzn file, it just has `solve  satisfy;` in it and nothing else.

I'm using MiniZinc 2.3.2 on Windows.

**Comment by guidotack** [comment]
The case for n=50 in the IDE is definitely a bug (I'll have to look into it a bit more to understand what's going on).
Unfortunately, the case for n=10 (or n=50 on the command line) is correct, even though it's certainly not intuitive. The problem is that output items are special in MiniZinc, they are evaluated together with the actual output. But all other items, including the declaration of the array `A` in your example, are evaluated when the model is compiled (i.e., before solving it). Effectively, this means that you can't decompose output like this, because you didn't tell MiniZinc that it should only evaluate `A` when the output is available. To achieve that, you would have to declare `A` inside a `let`:

```
output let {
  array[1..n] of string: A = [show_int(2, x) | x in a];
} in [join("  ", A)];
```

Or, alternatively, define a function that you call from the output item:

```
function array[int] of string: A() = [show_int(2, x) | x in a];
output [join("  ", A())];
```

Ideally, we'd have better error messages (or warnings) for this case. I'll put that on our todo list.

**Comment by tomerv** [comment]
Thanks for the quick and detailed answer!
From a user experience perspective, I think that an error would be preferred, where the error message says that it is invalid use. I find it very weird that the output statement prints the names of variables that I did not specify in my mzn file at all.
