### ISSUE TITLE
race condition in creating temp-files on windows (.fzn files)

### ISSUE THREAD

**Issue by rhorsak** [MiniZinc/libminizinc#349]
The TmpFile class from file_utils has an issue when temp-files are created.
Starting several processes at the same time from the host application causes sometimes the creation of identical filenames. This is because of the rename (MoveFile) which can lead to produce the same filename for another process.

Verified on Windows only.

As a quick fix I put in a short delay (GetTempFileName is based on the windows system time) to overcome the problem.

**Comment by guidotack** [comment]
I've pushed an attempt at fixing this (2d6909565b93e68cb8140bf62631cfd4fdd6616b) - unfortunately I don't have access to a Windows machine right now, so the code is completely untested.
My fix simply changes the MoveFile to CopyFile, so that the racing GetTempFileName still sees the old file and creates a new name. I'm keeping a vector of all the temp names and I remove them when the actual TempFile is destroyed. It would be great if you could give this a go and let me know if it works - if you can't test it right now, I'll run tests next week.
