### ISSUE TITLE
g12-lazy backend generates wrong solution (set_in_reif )

### ISSUE THREAD

**Issue by tofjw** [MiniZinc/libminizinc#35]
g12-lazy backend generates wrong solution.

test.fzn

```
var -10..10 : X1 :: output_var;
var bool : B1;

constraint set_in_reif(2, -3..3, B1);
constraint int_eq_reif(X1, 3, B1);

solve maximize X1;
```

flatzinc -b lazy test.fzn

```
X1 = 10;
----------
==========
```

flatzinc -b fd test.fzn

```
X1 = 3;
----------
==========
```

Similar problem will be happen with carpet-cutting benchmark included in MiniZinc 1.6 distribution.

**Comment by schutta** [comment]
The corresponding MiniZinc model would be like this

```
var -10..10 : X1;
var bool : B1;

constraint B1 <-> 2 in -3..3;
constraint B1 <-> X1 = 3;
solve maximize X1;

output [ 
    "X1 = ", show(X1), ";\n",
    "B1 = ", show(B1), ";\n"
];
```

MiniZinc 1.6 generates the following FlatZinc code, which will avoids the bug, because it will evaluate B1 true during flattening. Interestingly, MiniZinc 2.0.x won't evaluate B1 as true.

```
var bool: B1 :: output_var = true;
var -10..10: X1 :: output_var;
constraint int_eq_reif(X1, 3, true);
solve maximize X1;
```

However, g12-lazy is an obsolete Lazy Clause Generation (LCG) solver, which is not anymore maintained and has known bugs. If you want to use an LCG solver, please use Opturion CPX or chuffed.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
