### ISSUE TITLE
Counting constraints

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#354]
The first item on the list of changes describes a new way of specifying counting constraints and makes constraints  atmost/atleast/exactly deprecated. There is several problems with this.

First, your example "count(i in x)(x=3) <= 4" is incorrect. It should be "count(i in x)(i=3) <= 4", I guess.

Second, how can I get in my solver constraints  fzn_count_?_par generated when count_fn.mzn, that implements count function, generates a new variable. In the example above a variable with domain 4..n, where n is the length of list x.

Finally, are  fzn_count_?_par correct. What is their semantics? Just looking at the library definition of  fzn_count_leq_par we get

count(x,y) >= c

I would guess on count(x,y) <= c, that is the number of y in x is lower or equal c.

Did I missed something here?

/Kris

**Comment by guidotack** [comment]
1. Thanks, the example in the change log is indeed incorrect. The online version is now fixed.
2. You're correct, the two argument function `count(array[int] of var int, var int)` is currently not rewritten into the count predicates and will therefore create a variable. In the next release, this function will also be rewritten if it is used with a comparison operator, such as the `count(x,y) >= c` from your example. For now, you'd have to write your example as `count(i in x)(i=y) >= c`.
3. The _par versions are correct, they implement exactly the same semantics as the var versions. The "direction" of the comparison is the other way around compared to at_most/at_least, but it's always been like that (this is one of the reasons we wanted to deprecate one of the two versions, because it was confusing). So `count_leq(x,y,z)` means the count of y in x is less than or equal to z.

**Comment by krzku** [comment]
Referring to point 3. You mean that it is wrong in the current distribution? I have the following definition that seems to not follow your statement.

predicate fzn_count_leq_par(array[int] of var int: x, int: y, int: c) =
    count(x,y) >= c;

**Comment by guidotack** [comment]
No, it’s correct in the distribution (I had to edit my answer, please check it on GitHub again).
