### ISSUE TITLE
Returns ERROR for solvable CSP using Chuffed 

### ISSUE THREAD

**Issue by AML14** [MiniZinc/libminizinc#362]
Given the following mzn:

```
var int: p1;
var 0..1: p1Set;
var int: p2;
var 0..1: p2Set;
var int: p3;
var 0..1: p3Set;

constraint ((p1Set==1 /\ p2Set==1 /\ p3Set==1) -> (p1*p2*p3<5));
constraint p1Set = 1;
constraint p2Set = 1;
constraint p3Set = 1;

solve satisfy;
```

When using the Chuffed solver, it returns:

```
=====ERROR=====
```

Whereas when using the Gecode solver, it returns a (correct) solution:

```
p1 = 0;
p1Set = 1;
p2 = -2147483646;
p2Set = 1;
p3 = -2147483646;
p3Set = 1;
----------
```

I don't know if this is something related to the previous issue I submitted (#359) and therefore has already been fixed. Let me know if I'm missing something.

**Comment by guidotack** [comment]
This is not related to #359, it is a bug in Chuffed.
As an aside, if your model contains unbounded variables (like p1, p2, p3), the behaviour is really undefined (and MiniZinc should probably produce a warning). None of the solvers that work with MiniZinc can handle unbounded variables correctly, they will all either truncate domains to arbitrary bounds or produce an error. This is not something the MiniZinc compiler can avoid, it's due to the underlying solving technology.

**Comment by AML14** [comment]
Thanks for the answer, @guidotack, I may transfer the issue to Chuffed in that case.

So what would be the best approach then? Setting a domain for the variable that is large enough and suitable for my use case? Something like:

```
var -10000000..10000000: p1Set;
```

Or that would cause problems too?

**Comment by cyderize** [comment]
In your example you want to set bounds for `p1`, `p2` and `p3` (`p1Set` etc are fine already being set to `0..1`) similarly to the way you have described (assuming they all need the same bounds):
```
var -1290..1290: p1;
var -1290..1290: p2;
var -1290..1290: p3;
```
The problem more or less lies with the multiplication `p1*p2*p3` as the bounds for this is determined product of the lower/upper bounds of the individual variables, making it likely you will run into overflow issues. 

One of the bounds to worry about are the 64-bit int that minizinc uses. Due to the multiplication, we have to stay smaller than `cuberoot(2^63)=2097152` or minizinc will give an overflow error (that is, we can use `-2097151..2097151`). If you examine the flatzinc using these bounds, you will see an introduced variable with the bounds `-9223358842721533951..9223358842721533951`.

Then, solvers themselves likely cannot handle such large bounds. Many solvers only allow us to use 32-bit integers, and so we cannot have bounds greater than `-2147483648..2147483648` (2^31). Therefore, we'd have to restrict our domain even further to `-1290..1290` to keep the cube of that within range. In this case we have an introduced variable with bounds `-2146689000..2146689000`.

Chuffed can run into problems when dealing with bounds outside `-500000000..500000000` (although many things will work outside this), and especially so at the 32-bit limits (where overflows can occur) so you should be careful about variables (including introduced ones) which end up exceeding these bounds.

**Comment by AML14** [comment]
Thank you very much for the very clear explanation.
