### ISSUE TITLE
Timing information different in IDE and when running from console

### ISSUE THREAD

**Issue by sarafrim** [MiniZinc/libminizinc#366]
When I run my model in the IDE with "output timing information" checked, the "time elapsed" shows elapsed time without including the compilation time. However, if I run the same model from command line with flag --output-time , the elapsed time includes compilation time. My guess is that this is not the intended behavior? Or should I have another flag if I only want to see the actual solving time?

IDE:
% time elapsed: 2.96 s
%%%mzn-stat: initTime=1.727
%%%mzn-stat: solveTime=1.271

Console:
% time elapsed: 17.56 s
%%%mzn-stat: initTime=1.617
%%%mzn-stat: solveTime=1.084

**Comment by cyderize** [comment]
When you run the minizinc command, it performs both compilation and solving, so the time elapsed includes both of these. When running in the IDE, the compilation happens prior to solving, so the reported time does not include compilation.

You'd probably be better off adding up the initTime and solveTime if they are given by the solver (this should be more accurate than `% time elapsed` which may include some overhead from starting minizinc).

If you really want to mimic IDE behaviour it's possible to run something like:
```sh
minizinc -c --solver gecode model.mzn
fzn-gecode model.fzn | minizinc --output-time --ozn-file model.ozn
```

However due to console buffering, there may be differences. Some platforms/consoles may not start minizinc until the solver has output something, meaning you could get a very short (and useless) time elapsed.

**Comment by sarafrim** [comment]
Thanks for the reply. I was guessing this was the case. I'm not not that interested in the total time (initTime+solveTime) but more the timing of the intermediate solutions (which is why I have used the elapsed time). But now I know why it works like this, so I can figure out some workaround. Thanks!
