### ISSUE TITLE
Converting arrays to sets (array2set)

### ISSUE THREAD

**Issue by jarble** [MiniZinc/libminizinc#370]
I tried to convert an array to a set using `array2set`. This program compiles successfully, but it produces an error at runtime:

```
%These two arrays should have the same items, not in the same order
array[1..3] of var int:A0;
array[1..3] of var int:A1;
constraint forall(A2 in A0)((A2 in array2set(A1)));
```

When I run this program using the Chuffed solver, it shows this error:

```
Error: Unknown character in line no. 7
Error: syntax error, unexpected ID, expecting INT_LIT or INTTOK or '{' in line no. 7
```

Is it possible to correct this error, so that an array can be converted to a set?

**Comment by hakank** [comment]
If you add 

    include "nosets.mzn";

then it should  work. At least in principle. However,  the variables has infinite domain (`var int`) which cases the MiniZinc error:

    ....
    in array comprehension expression
        comprehension iterates over an infinite set

If the domains are finite (e.g. `var 0..10`) then most FlatZinc solvers can work with this model.

However, Chuffed throws the error

    Error: Registry: Constraint bool_lin_eq not found in line no. 76.

**Comment by krzku** [comment]
This is caused by the minizinc compiler translation. The set variable are translated to

var set of -infinity..infinity: X_INTRODUCED_6_ ::var_is_introduced ;
var set of -infinity..infinity: X_INTRODUCED_8_ ::var_is_introduced ;
var set of -infinity..infinity: X_INTRODUCED_10_ ::var_is_introduced ;
var set of -infinity..infinity: X_INTRODUCED_16_ ::var_is_introduced :: is_defined_var;
var set of -infinity..infinity: X_INTRODUCED_17_ ::var_is_introduced :: is_defined_var;

but in flatzinc grammar (section 4.3.6.) do not define "infinity" and solvers do not parse it. If you change manually these declarations to "var set of int:" then it should be parsed and solved.
