### ISSUE TITLE
-c "no solver selected"

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#394]
When downloading the bundle:
`MiniZincIDE-2.4.3-bundle-linux-x86_64`
the following call:
`./MiniZincIDE-2.4.3-bundle-linux-x86_64/bin/minizinc --stdlib-dir ./somewhere -G chuffed -c --output-fzn-to-stdout triangular.mzn triangular/n10.dzn`
works flawlessly, producing some flatzinc output.
When cloning the develop branch and compiling it manually with the following CMake Configuration:
```
-- The CXX compiler identification is GNU 7.2.0
-- The C compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /usr/local/apps/gcc/7.2.0/bin/g++
-- Check for working CXX compiler: /usr/local/apps/gcc/7.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
vi CM	-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/local/apps/gcc/7.2.0/bin/gcc
-- Check for working C compiler: /usr/local/apps/gcc/7.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file Windows.h
-- Looking for include file Windows.h - not found
-- Could NOT find CPlex, use CPLEX_ROOT to hint its location (missing: CPLEX_INCLUDE) 
-- Could NOT find Geas, use GEAS_ROOT to hint its location (missing: GEAS_INCLUDE GEAS_LIBRARY) 
-- Could NOT find Gecode, use Gecode_ROOT to hint its location (missing: GECODE_INCLUDE GECODE_LIBRARY Driver Float Int Kernel Minimodel Search Set Support) (Required is at least version "6.0")
-- Could NOT find Gurobi, use GUROBI_ROOT to hint its location (missing: GUROBI_INCLUDE) 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Could NOT find OsiCBC, use OsiCBC_ROOT to hint its location (missing: OSICBC_INCLUDE) 
-- Could NOT find SCIP, use SCIP_ROOT to hint its location (missing: SCIP_INCLUDE) 
-- Could NOT find Xpress, use Xpress_ROOT to hint its location (missing: XPRESS_INCLUDE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found BISON: /usr/bin/bison (found suitable version "3.0.4", minimum required is "2.3") 
-- Could NOT find FLEX (missing: FLEX_EXECUTABLE) (Required is at least version "2.5")

----- MiniZinc build configuration ----
MiniZinc version: 2.4.3 
Enabled drivers:
---------------------------------------

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ostrowsk/minizinc/libminizinc/build
```

the same call with my own binary results in the output:
```
Config exception: no solver selected
minizinc: MiniZinc to FlatZinc converter.
Usage: minizinc  [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...]
More info with "./programs/minizinc --help"
```

Is this intentional ? Do I need a solver installed just to convert from minizinc to flatzinc (maybe some preprocessing you are doing)? What is the difference between the prebuild bundle and my built...

Thanks a lot.

**Comment by Dekker1** [comment]
Hi @MaxOstrowski,

This is expected behavior. To avert the misconception that there is such a thing as generic FlatZinc, the compiler will force you to choose a solver configuration to force the notion that you are compiling for that solver. (You seem to do this using the `-G` flag, which is usually set by the solver configuration).

Why you don't see this behavior in the bundled version of MiniZinc is because it ships with a `Preferences.json` file which set Gecode as its default solver.

The compiler does allow you to work directly with the abstract FlatZinc interface by setting `--solver org.minizinc.mzn-fzn`. Note that you don't have to set a solver (executable) as long as you are using the `-c` flag.

All of this and a lot more is documented on our website:
 - [Command line Interface](https://www.minizinc.org/doc-2.4.3/en/command_line.html)
 - [Interfacing Solvers to Flatzinc](https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html)
