### ISSUE TITLE
Built-ins do not work with optimizations or Gecode solver

### ISSUE THREAD

**Issue by captn3m0** [MiniZinc/libminizinc#396]
System Details

```
5.6.15-arch1-1 x86_64 GNU/Linux
The MiniZinc IDE
Version 2.4.3
122689869
```

This is my sample file:

```zinc
enum Letters;

Letters = {A,B,C};

var Letters: a;
var Letters: b;
constraint a=A;
constraint b=B;

var set of Letters: d;

constraint d = set_diff(Letters,a..b);
```

Running against Chuffed with `-O1`  gets me the expected result:

```
a = A;
b = B;
d = {C};
% time elapsed: 0.02 s
```

But if I change to `-O2`,or try it on another solver like Gecode:

```
MiniZinc: type error: no function or predicate with this signature found: `set_diff(set of Letters,var set of int)'
Process finished with non-zero exit code 1
```

**Comment by guidotack** [comment]
The `set_diff` function is defined in the `nosets.mzn` library, which is a helper library for solvers that don't support set variables natively. It is therefore not available in MiniZinc models in general. Ideally, we would mark these functions as "internal" so that they can't be used in user models (or have some sort of namespacing for them), but for now, you will only get an error message like the one you saw.
