### ISSUE TITLE
Error with array literal of variables

### ISSUE THREAD

**Issue by Shaolun5** [MiniZinc/libminizinc#407]
Hi, here is the example to reproduce the error:
```minizinc
array[1..5] of var 1..10: a = [1,2,3,4,5];

var 1..100: s;
constraint s = sum(j in 1..3)([a[i]| i in 1..5 where a[i] != 3][j]);

output [show(s)]; % shows 3, but the correct answer should be 7
```
Also when I replace `1..3` by `1..4`, MiniZinc reports:
> Error: Unknown character in line no. 3

**Comment by cyderize** [comment]
The result `s = 3` is correct in that case, as since `a` is `var`, the array comprehension generates a hidden option type array (see [here](https://www.minizinc.org/doc-2.4.3/en/optiontypes.html#hidden-option-types) in the docs).

That is, the comprehension does not result in the array `[1, 2, 4, 5]` and sum the three elements 1, 2, and 4. Instead, it generates `[1, 2, <>, 4, 5]` and so the sum of the first 3 elements is 1+2+0=3 since the sum function treats `<>` as 0.

The error when replacing `1..3` with `1..4` will be fixed in the next release. Thanks!
