### ISSUE TITLE
Request: warn about variable shadowing

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#419]
I have wasted some time finding variable shadowing bugs.  For example:

```
array[1..3, 1..3] of var 1..2: x;

% intention: set x[1..2,1..2] to 1
% by mistake, I used i twice, instead of i and j
constraint
  forall(i in 1..2)(
    forall(i in 1..2)(x[i,i] = 1)
  );
```

Please, could minizinc issue warnings for that?

**Comment by guidotack** [comment]
Good idea, and easy to add. You will now get a warning when a variable shadows another variable in the same function, or if the expression is not inside a function, if it shadows anything in the top level. E.g., if you have a let inside a function that declares a variable `i`, you won't get a warning for a top-level variable also called `i` (otherwise you might get spurious warnings from library functions if you use any name that they use internally).
