### ISSUE TITLE
Error message for FindGecode.cmake misleading when Gecode found but MPFR not found

### ISSUE THREAD

**Issue by deliciouslytyped** [MiniZinc/libminizinc#433]
The error looks like this:
```
-- Could NOT find MPFR, use MPFR_ROOT to hint its location (missing: MPFR_LIBRARY MPFR_INCLUDE)
-- Could NOT find Gecode, use Gecode_ROOT to hint its location (missing: GECODE_LIBRARY) (found suitable version "6.2.0", minimum required is "6.0")
```
It looks like MPFR and Gecode are orthogonal, but MPFR is actually a requirement for CMake to succeed (I don't know if this is intended).

Total failure looks like this, so you realize something isn't right if you look long enough:
```
-- Could NOT find Gecode, use Gecode_ROOT to hint its location (missing: GECODE_INCLUDE GECODE_LIBRARY Driver Float Int Kernel Minimodel Search Set Support) (Required is at least version "6.0")
```
I originally thought somethng was wrong with `-DGecode_ROOT=...`

**Comment by Dekker1** [comment]
MPFR is only required if you want to compile the MiniZinc compiler with the internal Gecode component and that component has been build using MPFR.

Currently our find module for Gecode will just add the result of the find module for MPFR in this case. You are right that the error message is far from nice, but since find module (at least at the time of creation) don't have any decent way of setting their own dependencies, this is the best way I could come up with. I'm happy to accept PRs, if you have an idea about how to improve on this.

**Comment by deliciouslytyped** [comment]
It's probably a niche issue but I thought I should at least have it written down.
