### ISSUE TITLE
MiniZinc 2.5.3 flattening performance issue

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#448]
I am experiencing a flattening performance issue with a model for vehicle routing.

[cvrp.tar.gz](https://github.com/MiniZinc/libminizinc/files/5800706/cvrp.tar.gz) contains everything to reproduce the issue. There is a model and three instances of different sizes. The model is split into three parts: `cvrp_cp`, `cvrp` and `vrp`. These parts can be considered as a class hierarchy with `cvrp_cp` a subclass of `cvrp` and `cvrp` a subclass of `vrp` with superclasses declaring predicates and constants to be defined by subclasses. In particular, `vrp` declares and uses the predicate `delivery` implemented by `cvrp_cp`.

Reproduction steps:
```
tar xzf cvrp.tar.gz
cd cvrp
time minizinc -c cvrp_cp.mzn X-n469-k138.dzn
```
On my old i5 laptop, the runtime for this instance is about 40 seconds.

I managed to trace down the issue to the argument `TravelTimes` (a matrix) to `delivery`. When I remove this argument (and let `delivery` take `TravelTimes` from its environment), the runtime drops by an order of magnitude:

| |  `delivery` with `TravelTimes`  | `delivery` without `TravelTimes` |
| - | - | - |
| X-n101-k25  | 0.5s | 0.3s |
| X-n469-k138 | 40s | 5s |
| X-n1001-k43 | 103s | 9s |

You'll find the relevant code at the end of `vrp.mzn`; look out for the comments `SLOW` and `FAST`.

(Btw, the two variants of the model yield identical FlatZinc output.)

**Comment by Dekker1** [comment]
Just to elaborate on the problem. The problem here is that when using an exponential computational comprehension (`TravelTime`) as an argument to a custom predicate (`delivery`), there is seems to be a big overhead in the flattening time compared to when this comprehension is only stored globally in the environment.

It sounds as if the comprehension is evaluated multiple times when passed in as an argument.
