### ISSUE TITLE
`Run` or `Compile+Run` give different number of solutions

### ISSUE THREAD

**Issue by cprudhom** [MiniZinc/libminizinc#449]
Hi all,

I having the following problem: calling Run or Compile+Run on a model give different number of solutions (and different outputs btw).
I use MiniZinc 2.4.3 + Chuffed 0.10.4 [built-in] and try to solve a modified version of [vrp.mzn](https://gist.github.com/cprudhom/6e331f2e27c0a8a1a8862c212d45e02b#file-vrp-enum-mzn) with lighter data [data.dzn](https://gist.github.com/cprudhom/6e331f2e27c0a8a1a8862c212d45e02b#file-data-dzn).
The modification in the model is the following:
```mzn
% fix obj. value
constraint objective = 189;
solve 
    :: int_search(u ++ [x[i, j] | i in 1..N, j in 1..N],
        first_fail, indomain_min, complete) 
    %minimize objective;
    satisfy;
```
And I want to find all solutions  (using `-a`option in the configurator editor).
Using 'Run' directly on the mzn file returns 8 solutions.
Using 'Compile' to get a fzn file and calling 'Run' on this file returns 102 solutions.
As the same goes with Gecode 6.1.1 [built-in] or Choco, I suppose this is related to the conversion from mzn+dzn to fzn.

Can anyone help me on this issue?

Best regars,
CP

**Comment by cyderize** [comment]
It looks like the 102 FlatZinc solutions contains many duplicates (because of the solver following the search annotation) which are filtered out by MiniZinc when running normally.

**Comment by Dekker1** [comment]
Hi @cprudhom,

@cyderize's answer should point you in the right direction. MiniZinc does not require it solves to give unique answers when searching for all solutions. This is part of the output processing that MiniZinc performs afterwards. The answer MiniZinc gives is thus correct, there are 8 unique answers.

The question that is raised is then why the solver will report that there are 102 solutions. The answer to that question is that for the solver there actually can be more solutions because they don't just look at the output variables. A model instance often includes many auxiliary variable to help with the modelling of the problem or could be introduced in the decomposition of a global constraint. When searching for all (or even any) solutions, it is important that even the auxiliary variables are fixed to a value to ensure that all constraint in the model actually hold.

In your model, you provide a custom search strategy and this search strategy in this case changes the behaviour. Because your search strategy includes non-output variables, when the solver is called with the `-a` option. It will make sure to visit all values for the variables, included in the search strategy (which includes the solutions that are duplicated on the output variable values). The default search strategy smartly works from the output variables to avoid duplicate solutions.

I hope this explains why this isn't a issue in MiniZinc. I'll close this issue.

**Comment by cprudhom** [comment]
Hmmm. I was aware that Flatzinc returned too many solutions, but that seems inconsistent to me, since the Flatzinc file is expected to describe the same model and search that MiniZinc+data.

> This is part of the output processing that MiniZinc performs afterwards.

I was not aware that MiniZinc post-process resolution. Is it depicted somewhere in the documentation? 
Is it possible to disengage this filter in order to have similar behavior with Minizinc and Flatzinc (for instance, for some tests, I relied on fzn files because I don't want to convert all of them for each test campaign. 
Why Flatzinc not able to same output ? For instance, when I call MiniZinc with Chuffed or Choco as back-end solver, I suppose it creates a temporary Flatzinc file to be parsed and solved.

> In your model, you provide a custom search strategy and this search strategy in this case changes the behaviour. (...) The default search strategy smartly works from the output variables to avoid duplicate solutions

I used the model provided in the benchmark and simply turn it into a satisfaction problem. So do you think the model is not correct/complet?

Thank you for your help,

Best regards,
CP

**Comment by cyderize** [comment]
I believe you can run MiniZinc with the `--non-unique` option to turn off removal of duplicate solutions.

It looks like the duplicate solutions are due to having different values for `u` for the same value of `x`. If you add `u` to the `output` statement, you should be able to see this happening.

The search annotation `int_search(u ++ [x[i, j] | i in 1..N, j in 1..N], first_fail, indomain_min, complete)` essentially forces the solver to try values for `u` and values for `x`, but then since only `x` is output at the end, when the solver tries a different value of `u` with the same value of `x`, a duplicate arises. You can simply remove the search annotation if you don't want the solvers to do this and instead automatically figure out how to run the search.

In general, MiniZinc and FlatZinc do not always (or even usually) have the same output. MiniZinc has some language constructs which require post-processing of the solver output to recover the original value of the variables.

If you want to be able to pre-compile the models to FlatZinc and still maintain the normal output you'd get by running and compiling at the same time, you can do this from the command line (https://www.minizinc.org/doc-2.5.3/en/command_line.html#basic-usage) with the `-c` option to compile and then the `--ozn-file` option to recover the required output format from the solver output.

**Comment by cprudhom** [comment]
Thank you, that's clear now.
