### ISSUE TITLE
findMUS crashes on model with "var int" variable

### ISSUE THREAD

**Issue by gablin** [MiniZinc/libminizinc#450]
When I have the following model

`var int: X;`

and try to run

`$ findMUS model.mzn`

I get the following error:

`FznSubProblem:	hard cons: 0	soft cons: 0	leaves: 1	branches: 0	Built tree in 0.02046 seconds.
terminate called after throwing an instance of 'MiniZinc::InternalError'
  what():  MiniZinc: internal error
Aborted (core dumped)
`

Specifying a tighter domain than `int` solves the problem, but I wonder whether this should be considered a bug or not...
I tried this on the latest version (2.5.3) of minizinc.

**Comment by raphaelboudreault** [comment]
This bug still appears using findMUS with MiniZinc 2.5.5 with the same error message, and substituting all `var int` by `var 0..1000000` in my model seems to fix the problem. Further testing would be required.

**Comment by lokdlok** [comment]
Hi Raphael,

Sorry for the delay on getting back to you.
This is not a FindMUS bug. Though we should certainly have better error handling and messages.

MiniZinc does not define whether bounds should automatically be added to unbounded variables.
The internal `gecode_presolver` solver that FindMUS uses by default does not add these bounds.

The solution should be to add the `--allow-unbounded-vars` to the call to `gecode_presolver` (Or for findMUS: `findMUS model.mzn --solver-flags "--allow-unbounded-vars"`). 
Unfortunately I have spotted that the `--allow-unbounded-vars` flag gets consumed by the `minizinc` frontend when configuring a presolving step so that flag does not reach the solver.

The fix will require that we change the behaviour or the flags.

**Comment by gablin** [comment]
Thanks for your answer, Kevin.

Wouldn't a solution be to add that flag as given by default by findMUS when invoking gecode?

**Comment by Dekker1** [comment]
Moved issue to FindMUS repository: https://gitlab.com/minizinc/FindMUS/-/issues/4

**Comment by CervEdin** [comment]
> Hi Raphael,
> 
> Sorry for the delay on getting back to you. This is not a FindMUS bug. Though we should certainly have better error handling and messages.
> 
> MiniZinc does not define whether bounds should automatically be added to unbounded variables. The internal `gecode_presolver` solver that FindMUS uses by default does not add these bounds.
> 
> The solution should be to add the `--allow-unbounded-vars` to the call to `gecode_presolver` (Or for findMUS: `findMUS model.mzn --solver-flags "--allow-unbounded-vars"`). Unfortunately I have spotted that the `--allow-unbounded-vars` flag gets consumed by the `minizinc` frontend when configuring a presolving step so that flag does not reach the solver.
> 
> The fix will require that we change the behaviour or the flags.

Is there a work-around to this issue?
