### ISSUE TITLE
Chuffed version in bundled MiniZinc

### ISSUE THREAD

**Issue by raphaelboudreault** [MiniZinc/libminizinc#462]
Hi,
I'm working on Ubuntu 20.04.2 LTS. I dowloaded the most recent MiniZinc bundled binary packages (version 2.5.5) from the MiniZinc website with the _64 bit Linux binary archive (Ubuntu 16 or later)_ link.

Using the solver Chuffed 0.10.4 bundled, I am able to solve the following minimal problem test.mzn

```
var 0..100: x;
var 0..100: y;
constraint x < y;
solve :: int_search([y], smallest, indomain_median, complete) minimize x + y 
```
using `minizinc test.mzn --solver Chuffed` in command line.

However, looking at the source code of Chuffed 0.10.4, the **indomain_median** value selection heuristic should not supposed to be supported, or at least, not with this version. Compiling test.mzn to FZN and compiling Chuffed from source, the error is well thrown. 

Looking right now at the Chuffed repo, support for this heuristic seems to have been added in the _Update_mznlib_ or _develop_ branches. Maybe precise that Chuffed is compiled from these versions?

**Comment by Dekker1** [comment]
We currently bundle the `develop` branch of Chuffed. Since Chuffed is under very active development, we generally only merge fixes to match newer versions of MiniZinc into the `develop` branch, but we don't actively release newer versions of Chuffed. We probably should change this sometime, but at the moment sticking to the development version of Chuffed is probably the safest option if you want to match the version that MiniZinc uses.
