### ISSUE TITLE
Failure of the gecode solver on zebra_inverse.mzn: type error: no function or predicate with this signature found: `nvalue(var int,array[$_] of var int)'

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#474]
This problem http://hakank.org/minizinc/zebra_inverse.mzn fails:

```
Running zebra_inverse.mzn
/usr/local/share/minizinc/std/nvalue_fn.mzn:7.57-67:
MiniZinc: type error: no function or predicate with this signature found: `nvalue(var int,array[$_] of var int)'
Cannot use the following functions or predicates with the same identifier:
function var int : nvalue(array[$_] of var int: x);
    (requires 1 argument, but 2 given)
predicate nvalue(var int: n,array[int] of var int: x);
    (argument 2 expects type array[int] of var int, but type array[$_] of var int given)

Process finished with non-zero exit code 1
Finished in 210msec
```

minizinc-2.5.5
Gecode-6.2.0
FreeBSD 12.2

**Comment by hakank** [comment]
(Since it's my model, I comment here as well. :-))

I'm using minizinc 2.5.5 and fzn-gecode version 6.3.1 (from the MiniZincIDE distribution) and it works without any problem. Linux Ubuntu 18.05LTS.

**Comment by yurivict** [comment]
Their GitHub page says that 6.2.0 is the latest version: https://github.com/Gecode/gecode/tags

**Comment by hakank** [comment]
Note: I'm using the version of fzn-gecode that's included in the MiniZincIDE distribution, not the one from Gecode's distribution.

**Comment by yurivict** [comment]
@hakank I also have an unrelated question: Why there is no GLPK-based solver listed in http://hakank.org/minizinc/? Is this because there is some technical difficulty, or it's just that nobody wrote one yet?

**Comment by hakank** [comment]
I haven't seen of any GLPK FlatZinc solver, but perhaps there is one.

Regarding supported solvers, it's probably better to look at MiniZinc's list: https://www.minizinc.org/software.html .

**Comment by Dekker1** [comment]
Regarding the problem with Gecode, it seems that you once again bumped into the problem that MiniZinc sometimes uses development versions of Gecode and Chuffed to match the changes made in the MiniZinc library. The versions of the solvers themselves move a bit slower and are therefore not always up-to-date with the MiniZinc release. This is an issue that we hope to resolve in the future.

Regarding GLPK, I am not aware of a FlatZinc interface to the solver. So far I don't think there has been a need for such a solver interface since CBC seems to perform better (at least in all benchmarks I've seen) and GLPK doesn't have any extra features that MiniZinc could use.
