### ISSUE TITLE
Constraints on mod/div fail to finish using gecode

### ISSUE THREAD

**Issue by guillep** [MiniZinc/libminizinc#497]
The following script compiles ok, but never terminates when using gecode 6.3.0 backend.
Using Or-Tools (v11.2.3) finishes returning `=====UNKNOWN=====`

I can't tell if this script is unsatisfiable or I hit some solver limitation, thus the unknown on one side or the never-ending on the other. But the fact that it never terminates is fishy.

```
var int: x;
var int: y;
constraint x >= -1073741824;

constraint ((x mod y) = 0);
constraint (((x div y) >= -1073741824) /\ ((x div y) <= 1073741823));

solve satisfy;

output ["x=\(x)\n y=\(y)"];
```

**Comment by Dekker1** [comment]
The compilation from MiniZinc seems to be correct for both Gecode and OR-Tools for this model. Any problem would be with the solver not with the MiniZinc compiler.

Looking at the model I would guess that the problem is merely that the default search strategy will take a long time to find a solution. If you look at the search tree using Gecode Gist you will see that Gecode has a though time trying to find a valid value for `y` (it will try all possible values starting at -INT_MIN and then upwards). If you limit the domain of `y` to something more reasonable such as `var -1000000..1000000: y;` then the result is almost instant.
