### ISSUE TITLE
Using -t together with chuffed sometimes outputs no solution

### ISSUE THREAD

**Issue by gablin** [MiniZinc/libminizinc#523]
When I run chuffed with a timeout (-t flag) such that it does find a solution but is unable to prove optimality, minizinc may output no solution at all. I know that chuffed does find something if I include the -a flag - it's just that when only using -t it output nothing. If given a larger timeout value then it often works, but that shouldn't be necessary as it is known that chuffed does find a solution within the smaller timeout by adding the -a flag.

This is not a problem with fzn-chuffed as '-t' works fine when invoked directly. Moreover, minizinc does not even pass '-t' option to fzn-chuffed when using timeouts.

**Comment by Dekker1** [comment]
It looks like the declaration of the `-t` flag is missing in the Chuffed solver configuration: https://github.com/chuffed/chuffed/blob/81906e8b9ac264c9caf4df588f770d0c5dcda099/chuffed.msc.in#L9 This is the reason that the `-t` flag is not passed to Chuffed.

I'm pretty sure Chuffed handles the `-t` flag according to the [FlatZinc Interface](https://www.minizinc.org/doc-2.5.5/en/fzn-spec.html#command-line-interface-and-standard-options) specifications. So we should just add `-t` to the solver configuration.

Maybe a slightly different issue is that if `-i` (or old `-a`) is supported by a solver, but not `-t`, then maybe the MiniZinc driver should request the intermediate solutions so we have the last solution when the solver is interrupted.

**Comment by raphaelboudreault** [comment]
@Dekker1 While I thought that MR chuffed/chuffed#87 and chuffed/chuffed#88 would solve this issue, it still happens on Ubuntu 20.04.3 using MiniZinc 2.5.5. The flag -t is now passed correctly to Chuffed, but it seems like MiniZinc still kills Chuffed before it has the time to print anything. This can be seen using the flag -s, where Chuffed doesn't print any of its statistics when the timeout kicks in (when I'm pretty sure back in the days, it was doing so). Note that this behavior of missing output also happens when using Ctrl+C (only 'Interrupted' will be printed).
