### ISSUE TITLE
MZN 2.5.3: value_precede_chain assumes index set of its first argument is 1-based

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#530]
Following is a model that fails.  But if the uncommented line is replaced by either of the two commented lines, it succeeds. Apparently, `value_precede_chain` makes an unexpected assumption that the index set of arg 1 is 1-based. IMHO, that assumption is unwarranted.
```
include "globals.mzn";

array[1..10] of var 1..10: x;

constraint
	 value_precede_chain([1,3,5,7,9,2,4,6,8,10][6..10], x) /\
	 % value_precede_chain(array1d([1,3,5,7,9,2,4,6,8,10][6..10]), x) /\
	 % value_precede_chain([2,4,6,8,10], x) /\
	 true
;
constraint x = [i | i in 1..10];
```

**Comment by zayenz** [comment]
There is code in the decomposition that attempts to handle these cases generically (https://github.com/MiniZinc/libminizinc/blob/master/share/minizinc/std/fzn_value_precede_chain_int.mzn#L9), but I think it is buggy.  The code does a transformation of the values in order to make the set of values to disambiguate compact and contiguous. 

The first variant of your constraints produces FlatZinc lines like
```
constraint gecode_int_element(X_INTRODUCED_0_,1,[0,6,0,7,0,8,0,9,0,10],X_INTRODUCED_12_):: defines_var(X_INTRODUCED_12_);
```
while the second and third vaeriant produces the correct
```
constraint gecode_int_element(X_INTRODUCED_0_,1,[0,1,0,2,0,3,0,4,0,5],X_INTRODUCED_12_):: defines_var(X_INTRODUCED_12_);
```

The code uses the index as a proxy for the value to use in the output. Adjusting the code to account for the offset a non-1-index based start induces fixes this.

I'll make a PR for the fix.
