### ISSUE TITLE
`Config exception: no solver with tag gecode_presolver found`

### ISSUE THREAD

**Issue by chenrui333** [MiniZinc/libminizinc#546]
👋  trying to upgrade the formula to use the latest release, v2.6.0, but ran into some test issue.

```
==> /opt/homebrew/Cellar/minizinc/2.6.0/bin/minizinc --solver gecode_presolver satisfy.mzn
  Config exception: no solver with tag gecode_presolver found
```

I can somehow manage to pass the test by switching resolver to `coin-bc`, not sure if that is correct move. Thanks.

relates to https://github.com/Homebrew/homebrew-core/pull/95371

**Comment by cyderize** [comment]
In general this indicates that MiniZinc was not compiled with builtin Gecode enabled.

During configuration, CMake should output a list of `Enabled drivers` which should include Gecode if it was found.

I'm not familiar with how brew formulas work, but perhaps there needs to be a `-DGecode_ROOT=<somewhere>` option passed to `cmake` to help it find Gecode. On the other hand, I'm surprised that it would stop working now if it used to find it without that option, I'm not aware of any major changes to the way we look for Gecode since the previous release.

**Comment by chenrui333** [comment]
the homebrew test bot is basically using the underlying cmake to run the build, i can still see it fails with the following update

```diff
   def install
     mkdir "build" do
-      system "cmake", "..", *std_cmake_args
-      system "cmake", "--build", ".", "--target", "install"
+      system "cmake", "..", *std_cmake_args, "-DGecode_ROOT=#{Formula["gecode"].opt_prefix}"
+      system "cmake", "--build", ".", "--config", "Release", "--target", "install"
     end
   end
```

**Comment by Dekker1** [comment]
The problem that the Gecode release accompanying the MiniZinc release has been delayed. The current MiniZinc release does not compile with the version of Gecode that is currently released. The best/easiest fix would be to wait on the release on the release. However, undoing https://github.com/MiniZinc/libminizinc/commit/894d2d97b5d7c9a24a1b87d71f4c27f9e6a5f0e7 (using a patch) should also make the current version of MiniZinc usable using the already released version of Gecode

**Comment by Dekker1** [comment]
347337481a45e4a9cac4c63fe2f38147fc8cf079 also makes the current version of the MiniZinc compiler compatible with older versions of Gecode
