### ISSUE TITLE
MiniZinc: type error: identifier `_objective' already defined: big data.

### ISSUE THREAD

**Issue by alexeytref** [MiniZinc/libminizinc#564]
I have quite simple problem, but with big data. 
[problem.zip](https://github.com/MiniZinc/libminizinc/files/8349668/problem.zip)
```
int: nbRoutes;
var float: obj = 0;
solve  minimize obj;
```
If I run it from minizincIDE an error occurs
```
[problem:3.17-19](err:/C:/AlexeyFolder/ProductOptimization/problem/problem.mzn?line=3&column=17):
MiniZinc: type error: identifier `_objective' already defined
```
If I remove everything from the data except "nbRoutes", the error will disappear
Minizinc 2.6.2

**Comment by zayenz** [comment]
While I don't know the reason for the particular error, it is worth noting that the model-fragment you show has an issue in itself: the objective is fixed in the model. Since the objective to be minimized is given a fixed value, the problem turns into a satisfaction problem instead.

This might be from some test-case reduction you have done, but if not I thought I should mention it.

**Comment by alexeytref** [comment]
Yes, it was test-case reduction.

> While I don't know the reason for the particular error, it is worth noting that the model-fragment you show has an issue in itself: the objective is fixed in the model. Since the objective to be minimized is given a fixed value, the problem turns into a satisfaction problem instead.
> 
> This might be from some test-case reduction you have done, but if not I thought I should mention it.
