### ISSUE TITLE
Integer division and not_equals

### ISSUE THREAD

**Issue by IgnaceBleukx** [MiniZinc/libminizinc#568]
I am trying to solve a model with the following constraint:
```python
var 0..10: x;
constraint (x / 2) != 1;
```
This results in the following error:
`Error: Registry: Constraint float_lin_ne not found`

I am solving the model using Gecode 6.3.0.
Should I rewrite the model to use integer divisions or is this a bug in the Minizinc compiler?

**Comment by Dekker1** [comment]
This error means that Gecode currently does not support the float_lin_ne constraint. Normally the MiniZinc compiler assumes that FlatZinc builtins such as these are supported by the solver directly, or rewritten into constraints that are supported by the solver.

You might try and create an issue on the solver repository. However, currently this constraint is not supported by any of the major solvers, so the changes may be small.

As you said, using integer division is one alternative (and has most support among solvers). Otherwise, you can try and rephrase your constraint using `<`,`≤`,`>`, or `≥`, which are more likely to be supported by solvers.
