### ISSUE TITLE
Array sizes should be inferred at compile-time

### ISSUE THREAD

**Issue by jarble** [MiniZinc/libminizinc#598]
It seems that the MiniZinc compiler is unable to infer the size of an array at compile-time, even if its size is defined in a constraint.
For example:
```
array[int] of var int: var1;

constraint length(var1) == 3 /\ sum(var1) == 3;

solve satisfy;

output [show(var1),"\n"];
```

When I try to run this program, the MiniZinc compiler shows an error message:
`MiniZinc: flattening error: array dimensions unknown`

In this case, `var1` should be an `array[0..2] of var int`.

**Comment by Dekker1** [comment]
The title of the issue might be a bit misleading since sizes (and index sets) of arrays are often inferred in MiniZinc. We, however, do not currently infer the size (and index set) of an array through constraints in the model instance.

This might be possible, but would likely make the process very complex (or at least very dynamic). I don't see the advantage of this. The index set of an array can already be a complex expression that depends on data. Adding this type of inference weaken the type safety, without adding any additional functionality.
