### ISSUE TITLE
MiniZinc library lacks hooks for functions

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#603]
The Yuck MiniZinc binding overrides `global_cardinality_closed_fn`, `global_cardinality_fn`, and `bin_packing_load_fn`. Now, when a model imports `globals.mzn`, the MiniZinc compiler issues the following warnings:

```
Warning: included file "global_cardinality_closed_fn.mzn" overrides a global constraint file from the standard library. This is deprecated. For a solver-specific redefinition of a global constraint, override "fzn_<global>.mzn" instead.

Warning: included file "global_cardinality_fn.mzn" overrides a global constraint file from the standard library. This is deprecated. For a solver-specific redefinition of a global constraint, override "fzn_<global>.mzn" instead.

Warning: included file "bin_packing_load_fn.mzn" overrides a global constraint file from the standard library. This is deprecated. For a solver-specific redefinition of a global constraint, override "fzn_<global>.mzn" instead.
```

However, the `fzn_<global>` counterparts to these functions do not exist in the library.

**Comment by Dekker1** [comment]
If I'm not mistaken, then when we discussed this we were hoping that there would be a single override point for each of these functions at the `fzn_` predicate (so that's why there is no `fzn_` version of the functions). Since the conversion to a relational format has to happen anyway, I'm wondering why it would be necessary to override the functional versions.

Could you elaborate on why you need the overridden versions of these functions? Quickly comparing the yuck library and the standard library it mainly seems that we are overlooking from `defines_var` annotations in the standard library, but I think those could just be added there. Are there any other differences?

**Comment by informarte** [comment]
Yuck needs the overrides because it needs to know which variables a constraint defines. There are no other differences. However, all these functions define multiple variables, and that's why the overrides do not use `defines_var` but `defines_vars` (note the plural) defined by `yuck.mzn` as follows:

```
annotation defines_vars(array[$I] of var $T: x);
```

**Comment by Dekker1** [comment]
I don't have any objections against added this annotation to the standard library. I think we were already considering the "defining" relationship for arrays of variables in new prototypes for the compiler. This seems like a good first step in the current compiler.

I will discuss this with the other MiniZinc developers and get back to you
