### ISSUE TITLE
Feature request: how to gain insight into how a maximum was found, or search space was pruned

### ISSUE THREAD

**Issue by dan1221** [MiniZinc/libminizinc#612]
I have found the Chuffed solver to be spectacularly effective at some maximization problems.  But I am at a loss to know how it was able to effectively prune the search space.  Are there optimizations that can be individually disabled, so that I could see which optimizations are having the most effect?  Or is there a "verbose" mode that would show what it is pruning?  Can I learn anything just from knowing that Chuffed is much faster than Gecode on my problem?  I would like to be able to write an imperative program that can similarly prune the search space.

**Comment by zayenz** [comment]
Chuffed, as most solvers for combinatorial problems, uses a variety of techniques that work in conjunction to solve problems. In fact, even understanding how modern SAT solvers work is in itself [a research problem in it's own right](https://jakobnordstrom.github.io/docs/publications/PracticalCDCLinsights_IJCAI.pdf). Both Gecode and Chuffed have  many publications for various features, and they both draw on decades of research into constraint programming systems and for Chuffed also SAT solving.

In addition, a problem in general is that many of the methods are only useful on larger instances. Tracing individual propagations/restarts/learned clauses are typically quite uninformative.

As for the difference between Gecode and Chuffed, the most important difference for most casual users is that Chuffed has a good default search. Gecode typically needs a well-crafted search specification to shine. This is due to Chuffed being a lazy clause generation solver that uses a SAT solver internally for propagation and for search guidance. 

For understanding the behavior of solving a model, Gecode Gist can be used to see how the search-tree for problems look like for Gecode. That can sometimes be quite useful as a way to understand the shape of a tree, what search decisions are made, and so on. There are also some interesting profiling tools in the MiniZinc IDE that can be experimented with using the "Profile search" command (MiniZinc menu or the play-button drop-down).

There are several parameters that can be supplied to both Gecode and Chuffed. In the MiniZinc IDE you can add parameters in the solver configuration sidebar. Gecode has some, where I would suggest adding restarts and nogoods as that can help quite a bit for some types of problems. Chuffed has many parameters, but I don't know much about how they influence Chuffeds behavior.

Also, it is worth installing OR-Tools as an additional solver as it can be quit useful for some problems.
