### ISSUE TITLE
MiniZinc in browser or online

### ISSUE THREAD

**Issue by dan1221** [MiniZinc/libminizinc#613]
Is there an implementation of MiniZinc online, such as at ideone.com, or that works in a browser, so it can be used without installing locally?  It might be handy for Chromebooks.

**Comment by Dekker1** [comment]
There has been development on an early version of a web-based IDE for MiniZinc: https://gitlab.com/minizinc/minizinc-webide

We definitely see a future here, but there are quite a few challenges there. Especially since web-based MiniZinc cannot (easily) use FlatZinc solvers in separate processes to solve the problem instances.

I will close this issue, as this is not the best location to track a feature like this.
