### ISSUE TITLE
Issue when running ortools

### ISSUE THREAD

**Issue by ndangtt** [MiniZinc/libminizinc#622]
Hello,

When I try to call ortools via minizinc 2.6.4, I get the following error message:

```
Error: type error: function with the same type already defined in /Users/nttd/softwares/minizinc-2.6.4/share/minizinc/gecode/redefinitions.mzn:83.1-91.9
/Users/nttd/softwares/minizinc-2.6.4/share/minizinc/ortools/redefinitions-2.0.mzn:20.1-29.7
```
The issue disappeared when I reverted back to MiniZinc 2.5.5. Could you please help to have a look at it?

Thank you,
Nguyen

**Comment by Dekker1** [comment]
Hi Nguyen,

The error occurs because the OR-Tools repository added a definition to their MiniZinc library that was removed by mistake from the standard library. When the definition was added back in a patch release, this error started to occur. A temporary work-around is to remove the definition from the `ortools/redefinitions-2.0.mzn` file. The issue was resolve in a [recent commit](https://github.com/google/or-tools/commit/45c608e371d450a3dbace5462ed7e8cedea251ad) to the or-tools repository, so should be solved when this is included in a release.
