### ISSUE TITLE
Infeasible solution in output

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#638]
Consider this model:

```
array[1..2] of var bool: arr;

var 1..2: foo ::output = max(i in 1..2 where forall(j in 1..i)(arr[j]))(i);

constraint arr[2];
```

When enumerating all solutions, MiniZinc outputs:

```
arr = [true, true];
foo = 1;
----------
arr = [true, true];
foo = 2;
----------
==========
```

The first solution is infeasible. After some debugging, it appears an essential constraint gets removed here:

https://github.com/MiniZinc/libminizinc/blob/2e0bc37ae5b142e138f2129a04f0bb9db13bb8c0/lib/chain_compressor.cpp#L242

This happens with Gecode and OR-Tools. Interestingly, Chuffed gives *only* the infeasible solution.

**Comment by Dekker1** [comment]
The simplest form with this problem is probably:

```
array[1..2] of var bool: arr;
constraint arr[2];

var 1..2: foo ::output = max(
  [if forall([arr[j] | j in 1..i]) then i else <> endif| i in 1..2]
);
```

The code where you are pointing to is the chain compression which, combines implications when allowed. There might be a problem there, but currently I cannot find it. This is the trace of the chain compressor:

```
add constraint clause([X_INTRODUCED_9_], [X_INTRODUCED_0_]);
add constraint clause([X_INTRODUCED_12_], [X_INTRODUCED_0_]);
rm var bool: X_INTRODUCED_13_ ::var_is_introduced  :: ctx_pos = 
    forall([X_INTRODUCED_9_, X_INTRODUCED_12_]);
rm constraint clause([X_INTRODUCED_13_], [X_INTRODUCED_0_]);
----
add constraint int_eq_imp(X_INTRODUCED_10_, 1, X_INTRODUCED_0_);
rm var bool: X_INTRODUCED_12_ ::var_is_introduced  :: ctx_pos = 
    int_eq(X_INTRODUCED_10_, 1) :: maybe_partial;
rm constraint clause([X_INTRODUCED_12_], [X_INTRODUCED_0_]);
----
add constraint clause([X_INTRODUCED_0_], [X_INTRODUCED_22_]);
add constraint clause([X_INTRODUCED_1_], [X_INTRODUCED_22_]);
rm var bool: X_INTRODUCED_14_ ::var_is_introduced  :: ctx_mix = 
    forall([X_INTRODUCED_0_, X_INTRODUCED_1_]);
rm constraint clause([X_INTRODUCED_14_], [X_INTRODUCED_22_]);
----
add constraint clause([X_INTRODUCED_26_], [X_INTRODUCED_0_, X_INTRODUCED_22_]);
rm constraint clause([X_INTRODUCED_26_], [X_INTRODUCED_0_, X_INTRODUCED_1_]);
rm constraint clause([X_INTRODUCED_1_], [X_INTRODUCED_22_]);
----
```

I'm wondering if the problem stems from the option types, since the problem disappears when zero is used instead of absent.

**Comment by Dekker1** [comment]
Just as a small explanation, the problem turned out to indeed be in the chain compression. The selection criteria for the clauses being combined didn't consider the fact that the domain might have been set (and thus is an additional constraint).

The commits merged yesterday move the final propagation step to before the chain compression (making this less like or hopefully impossible), and the selection criteria have been adjusted to correctly consider this fact.
