### ISSUE TITLE
Feature request: support for bit fields

### ISSUE THREAD

**Issue by i-kudryavtsev** [MiniZinc/libminizinc#641]
Hi,

First, thanks a lot for a MiniZinc; it's great! 

I suggest the support of bit fields as datatypes. For example, it could be useful to model for modern hardware modeling to use 64-,128- or even more bit-fields. Right now, I can't use integers because minizinc works only with 32-bit integers (signed). I can model it as an array of bools or 0..1 ints, but, in this case, all operations should be defined on arrays, and propagation works very slowly and inefficiently. 

Please, consider if it's possible to support bit-fields. Thanks a lot!

Ilya

**Comment by Dekker1** [comment]
Maybe I misunderstand, but if you want to model bits separately, then (arrays of) booleans are indeed the best option. Different from C and other such languages, the memory that of a `bool` vs a `bit` is not generally an issue. These types have generally been optimised within the solvers, and within the MiniZinc compiler.

The main different that you can make is by choosing a solver that specialises in working with boolean decisions, such as SAT, MaxSAT, ASP, or maybe LCG solvers. Currently MiniZinc can connect to PicatSAT (MaxSAT), Chuffed (LCG), Potassco (ASP), and OR-Tools (LCG). There also exists an experimental setup to other SAT/MaxSAT solvers that we might be able to help you with if none of the other options work for you.

If you are still reasoning about the integers that are represented by the bits, then using integers would indeed be a better option. Generally you should be able to use MiniZinc integers to represent signed and unsigned types (by changing the domains), but they are limited to 64 bits (signed) or the number of bits supported by the targeted solver.

**Comment by i-kudryavtsev** [comment]
Yes, you understand it right, for sure. Thanks for the detailed answer!

My main problem is large integers. It especially works slowly if I need to work with arrays of large integers with variable indexes. Indeed, I represent my integers as boolean arrays, but I also need to support different constraints, mostly simple ones: equalities. However, it works badly for even not-so-big tasks: if I use ints, Gecode can solve the problem in a couple of seconds, and if I change representation to the boolean arrays, the same problem hangs. I understand that Gecode could be unsuitable for such problems, and, indeed, Chuffed could solve the problem quickly (also in two seconds). 

Analyzing the problem, I thought that the new type for the long Integers could be useful because, from my point of POV, the efficient propagators could be written for, at least, some simple and most useful constraints (and will drastically reduce the number of vars and constraints). 

Also, using LCG solvers (I don't know about SAT and ASP), I can't use different search strategies efficiently (as I understand it); for example, the random one is very important for me since I need to generate random solutions. 

p.s. It looks like MiniZinc works only with 32 bits literals. Even less because the following code 
```
var int: a;
constraint a = pow(2, 31); // but var int: a = pow(2, 31); works fine somehow
```

Produces the error:
```
Error: The literal '2147483648' of the type int is out of range (-2147483646..2147483646) in line no. 1
Error: syntax error, unexpected FZ_DOTDOT in line no. 1
```

**Comment by Dekker1** [comment]
CP solvers could indeed support "big integers", but I'm currently not aware of one that does. Once solvers arrive that have such support, then adding support from the MiniZinc side might be interesting.

LCG solver can still use the same search strategies as CP solvers, but they generally also use information from the SAT solver to make smart search decisions. (In MiniZinc disabling the "free search" option should generally enforce the solver to follow the search annotations when supported.

If the problem is merely to get random search decisions, then most other solver will be able to do the same. When many different solutions exists to the model, then for example changing the random seed for a SAT solver will likely also give different solutions.

Finally, the error that you show is an Gecode error when it reads the produced FlatZinc, it only supports 32 bit integers.

Why the direct assignment (`var int: a = pow(2, 31)`) is because it is fixed during compilation and will never make it to the solver.

**Comment by i-kudryavtsev** [comment]
Ok, I see; thanks a lot!
