### ISSUE TITLE
Globalizer does not work

### ISSUE THREAD

**Issue by vdijken** [MiniZinc/libminizinc#650]
I installed manually the latest version on Linux. Everything works fine except the globalizer. In the IDE I get: `Invalid option `-G'`. On the command line I get `minizinc-globalizer: ./mznlib/globalizer/both-glob.mzn: openBinaryFile: does not exist (No such file or directory)
`.

**Comment by cyderize** [comment]
Running using the IDE/`minizinc --solver globalizer` will be fixed in the next patch release.

As a workaround for now, you should be able to run `minizinc-globalizer` directly from the command line, if you add the option `-I <path/to/share/minizinc/globalizer>`:
```
minizinc-globalizer -I ../share/minizinc/globalizer test.mzn data.dzn
```

**Comment by vdijken** [comment]
The command line option minizinc-globalizer is even not mention in the latest manual!

**Comment by cyderize** [comment]
This is because you typically should not have to run it using the `minizinc-globalizer` binary. It should normally be run using `minizinc --solver globalizer`, which runs the `minizinc-globalizer` command with the correct arguments, except that it is currently broken, so you will have to use `minizinc-globalizer` directly until it is fixed in the next release.
