### ISSUE TITLE
Differing outputs when FlatZinc code is passed via stdin vs. file

### ISSUE THREAD

**Issue by chillja** [MiniZinc/libminizinc#655]
When running the following FlatZinc file `minimal.fzn`:
```
var 1..2:X_INTRODUCED_0_:: output_var;
var 1..2:X_INTRODUCED_1_:: output_var;
array[1..2] of var int:foobar:: output_array([1..2]) = [X_INTRODUCED_0_, X_INTRODUCED_1_];
constraint int_ne(X_INTRODUCED_0_, X_INTRODUCED_1_);
solve  satisfy;
```
with `cat minimal.fzn | minizinc --input-from-stdin --solver Chuffed` (or gecode) the output only prints the int vars:
```
X_INTRODUCED_0_ = 1;
X_INTRODUCED_1_ = 2;
----------
```
but when running `minizinc --solver Chuffed minimal.fzn` (or gecode) the output also correctly outputs the variable array:

```
X_INTRODUCED_0_ = 1;
X_INTRODUCED_1_ = 2;
foobar = array1d(1..2,[1, 2]);
----------
```

I am not (yet) familiar enough with the libminizinc code base to make any educated guess, where this might come from, or whether this is user error, but I think both should output the array.

**Comment by Dekker1** [comment]
The difference between the two commands is that when using `--input-from-stdin` the MiniZinc compiler will expect the input to be a MiniZinc model (`.mzn`).

In a MiniZinc model, FlatZinc annotations (`output_var` and `output_array`) are ignored. The default rules are then used to determine the output. In this case the variable are added, because they are decisions, but the array is not because it has a definition in its declaration.

As far as I know, there is currently no input from stdin that would allow you to pass in FlatZinc (as FlatZinc) to the compiler. However, some solvers do allow this.

**Comment by cyderize** [comment]
I believe there is an argument `--input-is-flatzinc` which can be used to inform MiniZinc that the input is FlatZinc. Combining it with the `--input-from-stdin` flag should give the correct results.

**Comment by chillja** [comment]
Thanks a lot! If appreciated I'd like to add `--input-is-flatzinc` to the reference manual, as a remark on the `--input-from-stdin` option.

**Comment by Dekker1** [comment]
Feel free to send a pull request. The `--help` information is printed using the `printHelp` function found in `flattener.cpp`
