### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by vdijken** [MiniZinc/libminizinc#658]
Installed the 2.7.1 version in Linux 64 from .tz file. Calling from the command line gives the error:
`/home/<me>/MiniZinc/bin/fzn-gecode: error while loading shared libraries: libQt6PrintSupport.so.6: cannot open shared object file: No such file or directory`
But the file is present:
```
ls -la  ~/MiniZinc/lib/libQt6PrintSupport.so.6
-rwxr-xr-x 1 <me> <me> 503104 mrt 31 03:02 /home/<me>/MiniZinc/lib/libQt6PrintSupport.so.6
```
```

**Comment by Dekker1** [comment]
Although we did change some of the details for the Linux MiniZinc release, this sounds like you might just be forgetting to set your library path to include the libraries included with the MiniZinc release. Did you set the environment variables like explained in the installation instructions: https://www.minizinc.org/doc-2.7.1/en/installation.html#archive ?

**Comment by matsc-at-sics-se** [comment]
There is a problem with setting environment variables like that. Some of the libraries are quite toxic to other apps.  For example:
```
$ LD_LIBRARY_PATH=/opt/MiniZincIDE-2.7.1-bundle-linux-x86_64/lib cp a b
cp: /opt/MiniZincIDE-2.7.1-bundle-linux-x86_64/lib/libselinux.so.1: no version information available (required by cp)
```
This is on Ubuntu 22.04.2 LTS.

**Comment by Dekker1** [comment]
This is why the AppImage is my preferred way of packaging for linux, since it actually makes sure that the libraries packaged with the executables are only used for the executables.

If you have troubles with incompatibilities on the system, then the solution is to either switch to one of our packages that already resolve these problems (i.e., AppImage or Snap), or to create a wrapper script for each of the executables that you want to run from command line such that is enables the libraries when running the library. An example is found in the IDE repository for the MiniZinc IDE: `MiniZincIDE.sh`

```
#!/bin/sh
DIR=$(dirname $(readlink -f "$0"))
[ -n "$XDG_RUNTIME_DIR" ] && mkdir -p $XDG_RUNTIME_DIR -m 700
export LD_LIBRARY_PATH="$DIR"/lib:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH="$DIR"/plugins

if ldd "$DIR"/bin/MiniZincIDE | grep -q 'libnss3.so => not found' ; then
    export LD_LIBRARY_PATH="$DIR"/lib_fallback:$LD_LIBRARY_PATH
fi

exec "$DIR"/bin/MiniZincIDE $@
```

Note that both AppImage and Snap can make the `minizinc` executable available on the command line, so that might be the quickest way.

**Comment by matsc-at-sics-se** [comment]
Thanks Jip. The wrapper script approach is satisfactory. I will try AppImage and/or Snap the next time.

**Comment by vdijken** [comment]
This only holds for the IDE.; not for the command line.

**Comment by cyderize** [comment]
With the release of 2.7.2, we now set the `RPATH` of `fzn-gecode` in the linux tarball so that it should be able to find the required libraries without needing a script to modify `LD_LIBRARY_PATH`, although your mileage may vary.
