### ISSUE TITLE
Segfault when testing with cbc v2.10.10

### ISSUE THREAD

**Issue by p-linnane** [MiniZinc/libminizinc#678]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v2.1010 of cbs we were doing some regression testing. minizinc segfaulted during this testing only on Linux. Here is the output:

```
  ==> /home/linuxbrew/.linuxbrew/Cellar/minizinc/2.7.2/bin/minizinc --solver gecode_presolver satisfy.mzn
  ==> /home/linuxbrew/.linuxbrew/Cellar/minizinc/2.7.2/bin/minizinc --solver cbc optimise.mzn
  MiniZinc error: Memory violation detected (segmentation fault).
  This is a bug. Please file a bug report using the MiniZinc bug tracker.
```

Relates to https://github.com/Homebrew/homebrew-core/pull/128715

**Comment by Dekker1** [comment]
Hi,

Thank you for contacting us with the problem. I would love to solve it, but I'm a little confused as to how the problem actually occurs. Using the latest version of MiniZinc and CBC built on Linux with GCC, we are not finding the same issue.

The only differences in the process that I can think of are that we are going from the development version of MiniZinc rather than the latest release, we use static linking in our MiniZinc builds, and I'm not sure if we are using the same version of GCC.

What is especially confusing is that the new version of CBC only contains a small header change according to the changelog that should most certainly have had the same effect if it was a problem in the development builds.

Is there an easy way to replicate the Homebrew build process in a docker container? This might help us create a development build with the right dependencies to and find where the segmentation fault happens.

**Comment by p-linnane** [comment]
Hello! Yes, we have a docker image you can use: https://hub.docker.com/r/homebrew/brew

**Comment by Dekker1** [comment]
Since this docker image is rather general, would you be able to provide a sequence of commands to recreate the issue in the container?

**Comment by p-linnane** [comment]
Sure thing. Here is a list of commands you can run:
```
export HOMEBREW_NO_INSTALL_FROM_API=1
cd Library/Taps/homebrew/homebrew-core
gh pr checkout 128715
brew install --verbose --build-from-source cbc
brew install minizinc
brew test --verbose minizinc
```

The GitHub Actions run in question may also be helpful: https://github.com/Homebrew/homebrew-core/actions/runs/4737775012/jobs/8414663423

**Comment by Dekker1** [comment]
I'm able to recreate the problem using your commands, but find that if I compile MiniZinc while installing `brew install --verbose --build-from-source minizinc`, then there is no problem.\

My guess would be that something in the CBC headers must be inlined by in a way by GCC that does not work between versions. Would it be possible to just make sure that MiniZinc is recompiled in the update of CBC?

**Comment by p-linnane** [comment]
Thanks for taking the time to look into this. I've confirmed rebuilding minizinc against the new cbc release resolves the issue! I appreciate your help and time.
