### ISSUE TITLE
Command line interpretation --output-time

### ISSUE THREAD

**Issue by vdijken** [MiniZinc/libminizinc#694]
When you accidentally put -output-time in the command line instead of --output-time, this not noticed as an error but the output goes into a file called utput-time.

**Comment by Dekker1** [comment]
This seems like expected behaviour to me since `-o` (and other single dash+letter flags) generally do not require a space before their arguments. For example, running `g++ -output-time test.cpp` will also create the output file `utput-time`

I suppose it seems unlikely that this is the wanted behaviour since we have an `--output-time` flag, but it seems like it would be a lot of programming effort for little gain in our custom CLI.
