### ISSUE TITLE
enum output

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/libminizinc#697]
Is the output of `enum I = anon_enum(5); array[I] of var bool: X; solve satisfy;` what is intended, with those `to_enum(I,i)` strings inside?

**Comment by Dekker1** [comment]
Hi Pierre,

`to_enum(I,i)` calls meant create members of an anonymous enumerated types.
The default DZN generated by the compiler is intended to be readable by the MZN/DZN parser. So in this case, the idea is that you can add 
```
X = [to_enum(I,1): false, to_enum(I,2): false, to_enum(I,3): false, to_enum(I,4): false, to_enum(I,5): false];
```
to your model (or as a seperate data file), and it will confirm the solution.
Because you have the `I` index set, the DZN format need to add the index set somehow. The default formatter will always create these indexed-array literals when you have an enumerated type as an index. This is equivalent in this case to `X = array1d(I, [false, false, false, false, false])'`.
