### ISSUE TITLE
minizinc-2.0: geost extreme cases

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#7]
Currently, a shape can be defined as an empty set of rectangles. Such a shape is arguably not too useful, and we certainly didn't mean to allow it when we came up with geost.

Another fine point: in SICStus, geost can take the option `bounding_box(Lower,Upper)`, which almost corresponds to the two extra arguments of `geost_bb`, but not quite.  SICStus requires that some objects actually reach `Lower` and `Upper`, whereas `geost_bb` provides a bounding box that allows a margin to the closest objects.

**Comment by schutta** [comment]
Thank you for pointing to the two differences. The shape one can easily be fixed by adding a check.

The second one is a little bit more tricky. My intuition is that a bounding box is an overestimation which contains all objects, but not necessarily the smallest/tightest box as in SICStus. From modelling point of view, there are cases for that the smallest bounding box is not asked or, maybe, counter-productive. How do you model such a case with geost in SICStus?

Maybe, a solution for that is to have two different "geost_bb" predicates in MiniZinc, one matching our definition and the other SICStus ones. Naming could be "geost_bb_leq" and "geost_bb_eq", or "geost_bb" and "geost_smallest_bb", or something else.

**Comment by matsc-at-sics-se** [comment]
I wouldn't worry about the bounding box issue. In my `fzn-sicstus`, I simply introduce the "tight bounding box" as another set of variables, then link the loose one and the tight one with <= constraints.
If I want to model a loose bounding box in SICStus with its `bounding_box(Lower,Upper)` option, I do the same thing: I introduce the loose bounding box as a set of variables and link the two.
I certainly would not litter the name space with yet more variants of `geost`.

**Comment by schutta** [comment]
I think that we go with two different versions of bounding boxes as mentioned above. It would nicely solve the issue.

**Comment by schutta** [comment]
An additional predicate called `geost_smallest_bb` was added to the MIniZinc library, which will be likely released in the next MiniZinc release.

Thank you again for pointing to this issue.
