### ISSUE TITLE
Warning about restart_none search annotation

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/libminizinc#701]
The search annotation `restart_none` is [listed](https://www.minizinc.org/doc-2.7.4/en/lib-stdlib-annotations.html?highlight=outdomain_min#mzn-ref-stdlib-annotations-search-restart-restart-none) as a valid search annotation.

However, it gives a warning:

```
$ cat r.mzn
var 1..5: x;
var 1..5: y;
var int: obj = x+y;
solve :: restart_none maximize obj;
output ["obj=\( obj )\n"];

$ '/Applications/MiniZincIDE.app/Contents/Resources/minizinc' r.mzn
Warning, ignored search annotation: restart_none
obj=10
----------
==========
$ '/Applications/MiniZincIDE.app/Contents/Resources/minizinc' --version
MiniZinc to FlatZinc converter, version 2.7.4, build 863757726
Copyright (C) 2014-2023 Monash University, NICTA, Data61
$ 
```

**Comment by Dekker1** [comment]
They are valid search annotations, but I'm afraid that solvers do not yet implement these search annotations. For Chuffed and Gecode, these solving strategies are available, but not read from their annotations. (Instead you can use the `--restart` flag these solvers provide).

Since this is something that needs to be implemented by the solvers, I will close the issue here.
