### ISSUE TITLE
option -O5 gives errors.

### ISSUE THREAD

**Issue by vdijken** [MiniZinc/libminizinc#755]
A model run by **minizinc -O5 model.mzn** runs fine under version 2.8.0 but gives errors under version `2.8.1.:`
```
Multiple type errors:
Error: type error: Type array[int,int] of bool is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
/MiniZinc/share/minizinc/gecode_presolver/fzn_table_bool.mzn:37.53-78

Error: type error: Type array[int,int] of int is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
/MiniZinc/share/minizinc/gecode_presolver/fzn_regular.mzn:38.19-42

```
The model does not have booleans but an 2-dimensional array containing 0 or 1. The only cause I see is that the optimizer changes the 0's and 1's in booleans. Without the option -O5 the model works fine,

**Comment by Dekker1** [comment]
It seems that when we adjusted the check to make sure that the FlatZinc declarations are correct, we didn't correctly check that the internal version of the Gecode library was compliant. 

Since the types were normally automatically corrected previously, patching the changes in the installed `mzn` library files would resolve the issue as a workaround.

**Comment by Dekker1** [comment]
Fixed in c438ae6

(seems I forgot the commit tag)

**Comment by vdijken** [comment]
Explanation for the reason why is clear. But have I wait until the next release before it is available? It is not clear to me how to perform the workaround in my environment.

**Comment by Dekker1** [comment]
If it helps, we are now also publishing the development builds of MiniZinc: https://github.com/MiniZinc/MiniZincIDE/releases/tag/edge
