### ISSUE TITLE
Comprehension segfault

### ISSUE THREAD

**Issue by wldhx** [MiniZinc/libminizinc#779]
Hi, here's a repro:

```
array[1..2] of var set of 1..2: xy_shapes;

array[int] of var opt set of 1..2: x_roff =
    [ {1}
    | l in 1..2, sh in xy_shapes[l] ];
```

```
MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.
```

```
> minizinc --version
MiniZinc to FlatZinc converter, version 2.8.2
Copyright (C) 2014-1980 Monash University, NICTA, Data61
```

**Comment by cyderize** [comment]
Unfortunately MiniZinc doesn't currently support `opt set` types.

In this case the comprehension iterates over a `var set`, and gets transformed into an array of `opt` under the hood - but since the comprehension returns `{1}` it tries to create a `var opt set` which is not supported.

Of course, this shouldn't crash with a segfault, so we'll have to fix the type checker to properly disallow the `var opt set` declaration, and the `var` comprehension with the set inside. In the future, we may have a look at trying to add support for `opt set`s so that this would be allowed.
