### ISSUE TITLE
Sometimes variables have incorrect domain?

### ISSUE THREAD

**Issue by wldhx** [MiniZinc/libminizinc#781]
Consider this simple code:

```
set of int: S = 1..2;

var 1..10: t1;
array[S,S] of var bool: occupancy;
constraint forall(i in S) (
        let { var S: x0 = t1;
              var S: x1 = x0 + 1; }
        in
           forall([ occupancy[l,w]
                  | l in x0..x1,
                    w in x0..x1 ])
);
```

In the let clause, x0/x1 are constrained to S and overflows are excluded by minizinc semantics.

However the code below gives warnings about OOB array access, while one expects the indices to be constrained by their type. (Sorry for the complex repro, that's as much as I could cut it down quickly. Some simpler versions don't exhibit this behaviour.)

```
% repro.mzn
int: length; % height of lake
set of int: LENGTH = 0..19;

int: ntypes;  % number of types of ship
set of int: TYPE = 1..ntypes;
array[TYPE] of int: number;         % number of each type of ship
array[SHIP] of TYPE: typ = [t | t in TYPE, s in 1..number[t]];

int: nshapes; % number of shapes
set of int: SHAPE = 1..nshapes;
set of int: SHAPE0 = 0..nshapes;
array[SHAPE] of set of ROFF: shape;

int: nroff; % number of rectangle offsets
set of int: ROFF = 1..nroff;
array[ROFF,1..4] of int: rectoff; % x offset, y offset, width, height

int: total_ships = sum(number);
set of int: SHIP = 1..total_ships;
array[SHIP] of var LENGTH:  x;
array[SHIP] of var SHAPE0:  k = typ;
    
array[LENGTH,LENGTH] of var bool: occupancy;
constraint forall(s in SHIP) (
    let { var SHAPE0: sh = k[s]; }
    in forall(r in shape[sh]) (
        let { var LENGTH: x0 = x[s] ;
              var LENGTH: x1 = x0 + 1; }
        in
           forall([ occupancy[l,w]
                  | l in x0..x1,
                    w in x0..x1 ])
    )
);

output "";

% repro.dzn
length = 20;

ntypes = 3;
number = [2,2,1];

nshapes = 3;
shape = [{1,2},{3,4,5},{6,7,8}];

nroff = 8;
rectoff = [| 0,1,2,1
           | 2,0,3,3
           | 0,1,1,2
           | 1,0,4,4
           | 5,0,2,2
           | 2,0,1,1
           | 1,1,3,3
           | 0,4,5,1
 |]; 
```

```
Warning: undefined result becomes false in Boolean context
  (array access out of bounds, dimension 2 of array has index set 0..19, but given index is 20)
```

(Here, LENGTH is 0..19, but x0/x1 is 20.)

```
> minizinc --version
MiniZinc to FlatZinc converter, version 2.8.2
Copyright (C) 2014-1980 Monash University, NICTA, Data61
```

**Comment by Dekker1** [comment]
I don't think this is a bug, but it might be a missed optimisation.
I think the problem in this case is that the array access is within the `forall` that iterates `r in shape[sh]`.
`shape[sh]` is a `var set of SHAPE` expression, which means that MiniZinc does not yet know exactly which shapes `r` should be considered. It will play it safe and "conditionally compile" for all potential `r`.

This conditional compilation means that the compiler won't directly enforce any constraints, but instead will add a constraint that says "if `r` is chosen, then apply this constraint".

In the case the constraint that you expected to be added is `x1 in LENGTH` (meaning `x[s] <= 18`. However, the compiler would have added `r in shape[sh] -> x[s] <= 18`.

With enough analysis, the compiler could have seen that the definition of `x1` (and `x0`) do not depend on `r`. Therefore, the expression could have been rewritten to further extract their definitions, resulting in:
```mzn
constraint forall(s in SHIP) (
  let {
    var SHAPE0: sh = k[s];
    var LENGTH: x0 = x[s];
    var LENGTH: x1 = x0 + 1;
  } in
  forall(r in shape[sh]) (
    forall([ occupancy[l,w] | l in x0..x1, w in x0..x1 ])
  )
);
```

Manually changing to this definition will reveal that this no longer has the out-of-bounds warning, because the compiler now enforces the domain constraint.

This type of analysis might be better suited for our new compiler infastructure. I will close this issue here.
