### ISSUE TITLE
about where condition constraining the context

### ISSUE THREAD

**Issue by FFages** [MiniZinc/libminizinc#804]
I was wondering what was the error reported or semantics of a "where" condition that constrains the decision variables of the context.
The following example illustrates the difficulty there is to interpret a constraint as an entailment check depending on the context:

% Use this editor as a MiniZinc scratch book
array[1..3] of var 1..2:A;
array[1..3] of var 1..2:B;
constraint forall (i,j in 1..3 where A[i]>B[j]) (A[i]<B[j]);
solve satisfy;

A = [1, 1, 1];
B = [1, 1, 1];

**Comment by FFages** [comment]
Of course one must understand that at compile time the where condition is not entailed so no constraint is posted for runtime but raising an error when a where condition involves decision variables might  perhaps be preferred ?

**Comment by Dekker1** [comment]
The `where` clause in MiniZinc's comprehensions (or comprehension calls) is equivalent to an "if-then" condition in the body of the comprehension. This means that the constraint is equivalent to 

```
constraint forall(i,j in 1..3) ( if A[i] > B[j] then A[i] < B[j] else true endif);
```

Since `A[i] < B[j]` is only enforced when `A[i] > B[j]`, it actually enforces `not (A[i] > B[j])`. Otherwise, it would be unsatisfiable.

Did you maybe mean to write the following constraint?

```
constraint forall(i,j in 1..3 where i < j) (A[i] < B[j]);
```

Note that it is fine to use decision variables in a condition, and these do not have to be entailed during compilation. The MiniZinc compiler will still take the condition into account.

**Comment by FFages** [comment]
Thank you for your answer.
It's just that I am writing in Prolog a MiniZinc interpreter not going through FlatZinc transformation (for several reasons) and I came to this question. 
There is no issue in fact ;-)
