### ISSUE TITLE
Index arrays with non-continuous sets

### ISSUE THREAD

**Issue by tobiasBora** [MiniZinc/libminizinc#846]
I'd love to be able to index some lists of elements based on some arbitrary numbers, that can be thought as ID. However, doing:
```
set of int: Men = {5, 12, 12};

array[Men] of var 0..100: age;

constraint age[12] == 42;

solve satisfy;
output ["age= \(age)"];
```
However, this fails with an error:
```
in variable declaration for 'age' MiniZinc:
evaluation error: array index set must be contiguous range
```
Would it be possible to allow arrays to be indexed with non-contiguous range, or provide some alternative (for instance by creating a special "dictionary/map" type?) to do something similar?

**Comment by Dekker1** [comment]
Using enumerated types and their constructors, this is allowed in the latest version of MiniZinc.

```mzn
enum Men = Man({5, 12, 12});

array[Men] of var 0..100: age;

constraint age[Man(12)] == 42;

solve satisfy;
output ["age= \(age)"];
```

We should update the error message to reflect this in future verisons.

**Comment by tobiasBora** [comment]
Nice trick, thanks a lot! Would be nice to have in the tutorial when introducing enums.

Also, is there any reason for not allowing the syntax:
```
age[12]
```
instead of `age[Man(12)]`?

**Comment by CervEdin** [comment]
> Nice trick, thanks a lot! Would be nice to have in the tutorial when introducing enums.
> 
> Also, is there any reason for not allowing the syntax:
> 
> ```
> age[12]
> ```
> 
> instead of `age[Man(12)]`?



> Nice trick, thanks a lot! Would be nice to have in the tutorial when introducing enums.
> 
> Also, is there any reason for not allowing the syntax:
> 
> ```
> age[12]
> ```
> 
> instead of `age[Man(12)]`?

My guess is that index sets in MiniZinc array _must_ be a continuous range.
Using an enum constructor simply maps a set into a continuous set of enums.

**Comment by Dekker1** [comment]
As Erik pointed out, the implementation of non-continuous index sets has more consequences for the underlying engine. We are not planning on implementing this feature in MiniZinc 2.
In the team we also decided not to make the error message more verbose.

For the workaround, the automatic coercion from integer to enumerated types is not supported. Although it might be clear for your case, it is not so clear in general. It would, for example, be possible for two enum constructors to accept the same integer argument. Since `Men(12)` would in this case be mapped to `2`, it might also just be as reasonable to expect the coercion to directly map from an underlying integer value.

In general we plan to strengthen the boundaries between enumerated types and integers. For example, it seems often unexpected that when using `Man(12)` is used in a integer position that it wouldn't map to `12`. (You would have to use `Man^-1(12)` for that). As such a MiniZinc 3, would likely see the removal of the automatic coercion of enumerated types to integers.

I will close this issue on this repository as we are not planning the implementation of non-continuous index sets for this compiler.
