### ISSUE TITLE
Various solvers fail

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#862]
Several solvers fail on the [food.mzn](https://www.freebsd.org/~yuri/food.mzn) problem and many other problems.

The OR Tools CP-SAT 9.8.9999 solver fails:
![image](https://github.com/user-attachments/assets/83d75215-15a5-4d29-865b-ce05a10cbf6f)

The JaCoP 4.8 solver fails:
![image](https://github.com/user-attachments/assets/4fe71f0f-036b-42cf-82a9-1bd7e4009443)

Couenne 0.5.8 solver fails:
![image](https://github.com/user-attachments/assets/942769f8-589d-41ec-86fe-9f56f3d31bb4)

Chuffed also fails.

What is going on with these solvers? They all worked before.

MiniZinc-2.8.7
FreeBSD 14.1

**Comment by krzku** [comment]
It works with JaCoP but you need to update your minizinc library to newest version, that is version 4.10. The minizinc compiler needs to have one dimensional arrays and old JaCoP library is therefore not compatible with newest minizinc compiler.

**Comment by guidotack** [comment]
I am almost certain that `food.mzn` never worked with or-tools, Chuffed and (as far as I know) JaCoP, because it uses float variables, which none of these solvers support. I suspect that the versions of those solvers that you're using are now incompatible with newer versions of MiniZinc. E.g. or-tools 9.8 is a year old, and JaCoP 4.8 is over 3 years old. Which version of Chuffed were you testing, and what was the error?
We're not testing regularly with Couenne, so there may be a problem there that we haven't noticed yet.

**Comment by krzku** [comment]
Just for clarification. JaCoP supports float variables since version 4.1.

**Comment by CervEdin** [comment]
> I am almost certain that `food.mzn` never worked with or-tools, Chuffed and (as far as I know) JaCoP, because it uses float variables, which none of these solvers support. I suspect that the versions of those solvers that you're using are now incompatible with newer versions of MiniZinc. E.g. or-tools 9.8 is a year old, and JaCoP 4.8 is over 3 years old. Which version of Chuffed were you testing, and what was the error? We're not testing regularly with Couenne, so there may be a problem there that we haven't noticed yet.

looks like it's also using quadratic constraints?
