### ISSUE TITLE
fzn_cumulatives: Argument min_m is redundant

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#869]
`fzn_cumulatives` is defined as follows:

```
% min_m is the first machine (which is the minimum, of the index set of b).
% For native implementations, you can subtract (min_m - 1) from the m array
% values to obtain 1-based machine numbers.
predicate fzn_cumulatives(array[int] of var int: s,
                          array[int] of var int: d,
                          array[int] of var int: r,
                          array[int] of var int: m,
                          array[int] of var int: b,
                          bool: upper,
                          int: min_m) =
  fzn_cumulatives_decomp(s, d, r, m, b, upper);
```
However, `min_m` is redundant because this information is readily available as `min(index_set(b)`, so it should probably be removed. (Neither `fzn_circuit` nor `fzn_inverse` have offset arguments.)

**Comment by Dekker1** [comment]
The extra argument is partially a response to several incorrect implementations of `fzn_circuit` that we've seen. In addition, we are now working with the assumption that everything on the FlatZinc level is 1-dimensional and 1-indexed.

Because of backwards compatibility, it is unlikely that `fzn_circuit` and `fzn_inverse` will change any time soon, but I believe they are more likely to change than `fzn_cumulatives`

**Comment by informarte** [comment]
Good to know that adding min_m was a deliberate design decision. Thank you for explaining.
