### ISSUE TITLE
LazyFD gives wrong result

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#96]
While trying to compare to the minizinc competition 2015 i found that the lazy solver returns a wrong optimum.

Given the competition benchmarks i did:
cat mznc2015_probs/spot5/spot5.mzn  mznc2015_probs/spot5/54.dzn > spot54.mzn
./mzn2fzn --output-to-stdout -G g12_lazyfd /mnt/scratch/ostrowsk/MINIZINK/combinedmznc2015_probs/spot5/spot5.mzn._54.dzn.mzn > spot54.fzn
flatzinc --ignore-user-search -b lazy -s spot54.fzn -a

The result is
objective = 36;

also all other solvers in the competition stated that it is 37.
Run on Debian7, MiniZinc2.0.13

Hope this helps,

Best,
Max

**Comment by schutta** [comment]
Thank you for reporting the issue with the solver G12/LazyFD. Since G12/LazyFD  is an obsolete Lazy Clause Generation (LCG) solver, which is not anymore maintained and has known bugs, we won't be able to fix it. If you want to use an LCG solver, please use Opturion CPX or [Chuffed](https://github.com/chuffed).
